### ISSUE TITLE
Exceptions being shown on dashboard is different from notifications

### ISSUE THREAD

**Issue by jfelchner** [bugsnag/bugsnag-ruby#165]
When we get a notification for certain errors in our application, the notification that we receive via Slack and/or Github is different than the error that we see on the web client dashboard.  The web client's error appears to be incorrect.

Example:

On the dashboard we see:

![image](https://cloud.githubusercontent.com/assets/285582/4396372/77abfa42-4434-11e4-837f-fb050844fba7.png)

In Slack, we see:

![image](https://cloud.githubusercontent.com/assets/285582/4396384/89957ba2-4434-11e4-9d05-bad187a124bb.png)

**Comment by jfelchner** [comment]
@ConradIrwin closed with no comment?

**Comment by ConradIrwin** [comment]
This doesn't make any sense to me at all — have you seen this problem since? If so, can you link me to the errors?

**Comment by jfelchner** [comment]
@ConradIrwin well then that would have been a better way to advance this issue than closing it without asking for more information IMO.

I no longer have access to the errors.  This issue was causing more problems than just having a different error show up in the dashboard vs in Slack.  Specifically we we were not able to properly ignore certain errors.  Since this issue wasn't responded to within any reasonable amount of time, we had to find a service that didn't have this problem and so we moved to Honeybadger.

I'm not sure what else you're looking for to get more info.  There's an error that shows up when the Slack notification is sent (as in the screenshot above) and there's an error that shows up when you click "details" (also in the separate screenshot above).  In a lot of situations for us they were two completely different things.

You can find our project here: https://bugsnag.com/the-kompanee-1/goodscout if you want to dive into it.  But like I said, we're on Honeybadger now so this no longer directly affects us.
