### ISSUE TITLE
Delayed_job queue locked after notification

### ISSUE THREAD

**Issue by ialiendeg** [bugsnag/bugsnag-ruby#170]
Using delayed_job, when some exception is raised in a job and the notification is sent by bugsnag (and email received), the queue is locked and no other job is processed after that.

This problem was noted with 1.8.6 version of the gem, but now with 2.5.0 version, the notification is logged in rails but email is not received neither is the exception in bugsnag dashboard.

**Comment by ConradIrwin** [comment]
This should have been fixed by `v2.6.0` and above.
