### ISSUE TITLE
How to notify ignored classes?

### ISSUE THREAD

**Issue by richardvenneman** [bugsnag/bugsnag-ruby#182]
The default configuration specifies several ignored_classes:

```ruby
DEFAULT_IGNORE_CLASSES = [
  "ActiveRecord::RecordNotFound",
  "ActionController::RoutingError",
  "ActionController::InvalidAuthenticityToken",
  "CGI::Session::CookieStore::TamperedWithCookie",
  "ActionController::UnknownAction",
  "AbstractController::ActionNotFound",
  "Mongoid::Errors::DocumentNotFound",
  "SystemExit",
  "SignalException"
].freeze
```

I actually want to keep track of `ActiveRecord::RecordNotFound` and `ActionController::RoutingError`. How can I unignore these classes? I tried setting an empty array trough the `ignore_classes` config writer but without any success.

**Comment by ConradIrwin** [comment]
@richardvenneman you should be able to do either:

```ruby
Bugsnag.configure do |config|
   config.ignore_classes = Set.new
end
```

or

```
Bugsnag.configuration.ignore_classes.delete  "ActiveRecord::RecordNotFound"
```

Please let me know if neither of those works for you.
