### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by mperham** [bugsnag/bugsnag-ruby#188]
I was quite shocked when I installed bugsnag gem and it pulled down 5 dependent gems.

multi_json has been deprecated for over a year now, e.g. https://github.com/sstephenson/sprockets/pull/440

I'd also like to see HTTParty removed and Net::HTTP used instead.

**Comment by ConradIrwin** [comment]
HTTParty is now gone.

multi_json will probably stay, because I don't like the idea of vendoring our own JSON code for 1.8.7 users. (Unfortunately, we have a significant number of users still using 1.8.7, so it's not feasible to drop support yet).

**Comment by mperham** [comment]
Thank you!
