### ISSUE TITLE
Travis build erroring on jruby during bundle install

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-ruby#190]
https://travis-ci.org/bugsnag/bugsnag-ruby/builds/45733904

**Comment by loopj** [comment]
Any ideas conrad?

**Comment by ConradIrwin** [comment]
It was broken before removing httparty; I think it's just a coincidence.
The failure is during bundle install, the tests pass on my local jruby

**Comment by loopj** [comment]
Thanks conrad, updated title :)
