### ISSUE TITLE
Exception from using path helper with bad data is ignored by default w Rails 4 < 4.2.0

### ISSUE THREAD

**Issue by red56** [bugsnag/bugsnag-ruby#195]
Because in Rails 4, bad paths (e.g. `edit_model_path(nil)`) generate UrlGenerationError and UrlGenerationError inherits from RoutingError (until Rails 4.2.0 see https://github.com/rails/rails/commit/8e1362be3fa8afa352a7acc4a1561205bcdada1e).

The default config for bugsnag excludes [ActionController::RoutingError](https://github.com/bugsnag/bugsnag-ruby#ignore_classes) (and all it's descendant classes -- this in particular may not be obvious to everyone). This means that a error in a template/helper (or indeed a controller) where a path is bad will not generate a Bugsnag report. 

NB: These path generation problems can come from data errors, and might only occur in deployment.

You can generate an example very easily by putting a 
```raise ActionController::UrlGenerationError.new('Simulating a dodgy path')```
in a controller (or passing the error into a template and raising it there).

A (bad) workaround for < rails 4.2.0 is to not ignore RoutingErrors: 

```
Bugsnag.configure do |config|
  config.ignore_classes.delete "ActionController::RoutingError"
end
```

There doesn't seem to be another workaround (i.e. there's no way to ignore JUST `ActionController::RoutingError` and not its descendants) other than allowing all through or updating to rails 4.2

I recognise this is really an error in Rails and not in Bugsnag, but none the less the problem is only seen as an exception notification problem, and there should be an adequate workaround for rails 4, <4.2. And it would be best to point out this problem.

**Comment by ConradIrwin** [comment]
@red56 you may be able to use the `before_notify_callbacks` hook mechanism to acheive this:

```ruby
# remove routing errors from default ignore
Bugsnag.configure do |config|
  config.ignore_classes.delete "ActionController::RoutingError"
end

# manually ignore routing errors, but not subclasses
Bugsnag.before_notify_callbacks << lambda{ |notif|
  notif.ignore! if notif.exceptions.first.class == ActionController::RoutingError
}
```

**Comment by red56** [comment]
@ConradIrwin -- Thanks for the workaround -- in the end we're going to upgrade to rails4.2 this week, so probably not worth fixing for now (might introduce other problems)

**Comment by ConradIrwin** [comment]
Great!
