### ISSUE TITLE
notifying bugsnag can fail with an encoding error

### ISSUE THREAD

**Issue by yob** [bugsnag/bugsnag-ruby#197]
We've come across a situation where notifying bugsnag of an exception can fail with an encoding error. Here's a simple script to reproduce the issue:

```ruby
s = "\"foo\xEBbar\"".force_encoding("utf-8")
begin
  JSON.parse(s)
rescue Exception => e
  Bugsnag.notify(e)
end
** [Bugsnag] Notifying https://notify.bugsnag.com of JSON::ParserError from api_key aaaaabbbbb
** [Bugsnag] Error fetching code: #<Errno::ENOENT: No such file or directory @ rb_sysopen - (irb)>
** [Bugsnag] Bugsnag middleware error: "\xEB" from ASCII-8BIT to UTF-8
** [Bugsnag] Middleware error stacktrace: [...] 
```

We're running bugsnag 2.7.1 with MRI 2.1.5 and rails 4.1.9.

**Comment by yob** [comment]
Thanks!

**Comment by strikyflo** [comment]
I can reproduce the error, using the snippet above, with the following configuration:

Bugsnag 2.8.1
MRI 2.2.1
Rails 4.2.1
