### ISSUE TITLE
Filtering from Rails.configuration.filter_parameters does not work in URLs

### ISSUE THREAD

**Issue by vandrijevik** [bugsnag/bugsnag-ruby#202]
In a Rails application, given the following configuration for filtering params:

```ruby
Rails.configuration.filter_parameters
=> [:password, :access_token, :refresh_token]
```

Bugsnag does not properly filter URLs that get sent across in the Request tab. In particular, given that configuration, the Bugsnag railtie [changes the Rails filters](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/railtie.rb#L21-L27) to strings that start with `\A` and end with `\z`, so we end up with:

```ruby
Bugsnag.configuration.params_filters
=> #<Set: {"password",
 /\Aaccess_token\z/,
 /\Arefresh_token\z/}>
```

As a result, [`Bugsnag.cleanup_url`](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/helpers.rb#L70-L76) does not match a URL that needs to be filtered properly:

```ruby
Bugsnag::Helpers.cleanup_url("https://host.example/sessions?access_token=abc123", Bugsnag.configuration.params_filters)
=> "https://host.example/sessions?access_token=abc123"
```

If Rails parameters are picked up unchanged (simulated by the direct assignment in the first line), `Bugsnag.cleanup_url` works as expected:

```ruby
Bugsnag.configuration.params_filters = ["password", "access_token", "refresh_token"]
Bugsnag::Helpers.cleanup_url("https://host.example/sessions?access_token=abc123", Bugsnag.configuration.params_filters)
=> "https://host.example/sessions?access_token=[FILTERED]"
```

I don’t know the motivation for modifying `Rails.configuration.filter_parameters` when including them in `Bugsnag.configuration.params_filters`, but I propose passing those values unmodified so filtering works properly everywhere.

**Comment by snmaynard** [comment]
We modify the Rails filters to do exact matching on the keys in the metadata, but unfortunately this seems to somewhat break cleanup_url. We should leave the filters as they are and simply deal with the \A and \z appropriately in there (possibly extracting out each parameter and testing it, rather than doing it as one huge string).

I'll try and get around to getting a fix out for this soon! Thanks for reporting!
