### ISSUE TITLE
Error reaches bugsnag even after being rescued and explicitly ignored

### ISSUE THREAD

**Issue by Draiken** [bugsnag/bugsnag-ruby#211]
We have a piece of code that started sending errors to bugsnag after we updated the gem.
It's a sidekiq worker and the code is basically:

    def perform
      do_thing # raises SomeError
    rescue SomeError => e
      Bugsnag.before_notify_callbacks << lambda {|n| n.ignore!}
      raise e
    ensure
      Bugsnag.before_notify_callbacks.clear
    end

Still we end up with bugsnag errors from `SomeError`. Is something wrong with this code? Is there a better way to ignore this specific error without adding it to the global ignored errors?

Thanks!

**Comment by ConradIrwin** [comment]
@Draiken I think there's just a timing problem. The ensure block happens immediately after the raise but before the error is caught, so your callback is getting cleared before Bugsnag sees the exception.

There are two possible solutions:

1. Just delete the ensure block, we already clear out the callbacks at the end of each sidekiq job.
2. Wrap this exception in a custom class, and then ignore that https://github.com/bugsnag/bugsnag-ruby#ignore_classes

Please let me know if you need more help figuring this out.

**Comment by Draiken** [comment]
Awesome!

Unfortunately this worked on bugsnag 1.4 (we were quite outdated) so it led me to believe the problem was on your side. Sorry!

Thanks for the quick response.
