### ISSUE TITLE
Initialization config (proxy settings) is not picked up by rake bugsnag:deploy

### ISSUE THREAD

**Issue by semaperepelitsa** [bugsnag/bugsnag-ruby#212]
In our production servers all outside network connections must go through a proxy. We configure it in Rails initializer:

```ruby
Bugsnag.configure do |config|
  if proxy = ENV['http_proxy'] || ENV['HTTP_PROXY']
    proxy_uri = URI(proxy)
    config.proxy_host = proxy_uri.host
    config.proxy_port = proxy_uri.port
    config.proxy_user = proxy_uri.user
    config.proxy_password = proxy_uri.password
  end
end
```

This works fine both for application and for `rake bugsnag:test_exception`. However, `rake bugsnag:deploy` does not load config and hence fails to connect.

In your code I can see that Bugsnag does not load application if API key is derived from BUGSNAG_API_KEY (assuming there is no config). We tend to use environment variables for all possible config settings including API keys. Sadly, Bugsnag does not pick up proxy from the standard http_proxy variable so we need to explicitly specify it. Even without proxy I can see at least two important config settings that cannot be specified by env: hostname and use_ssl.

I believe Bugsnag should always load application config as does test_exception task. Additionally, it would be great if it used http_proxy variable so we don't have to manually configure it. Net HTTP by default does use it but your library overrides defaults with nils from config.

I can make pull requests if you agree on my suggestions.

**Comment by jessicard** [comment]
Hey @semaperepelitsa - thanks for the suggestion! Unfortunately, we don't want to autoload the env for deploys. To autoload the env for deploys, the task will have to start up Rails, which will make deploys way slower. We only want to do that if it's necessary. We could, however, have a new rake task, like `rake bugsnag:deploy_loading_env` or something, OR have an ENV var to set, which could tell Bugsnag to load the Rails env. Thoughts?

**Comment by semaperepelitsa** [comment]
If bootup time is a concern I don’t think we should go that way. Is there any reason why Bugsnag doesn’t send deploy data automatically when application is being started? That would be a much simpler solution.

**Comment by snmaynard** [comment]
We dont do that because every time the app was started we would think it was a new deploy - and also all the revision information would have to be available all the time.

We may do some backed work to fix some of these issues in future, but right now bugsnag assumes when it hears about a deploy that it is different to the previous one.

**Comment by kattrali** [comment]
Closing this for now, we can revisit if there is additional suggestions about ways to tweak the deployment handling.
