### ISSUE TITLE
Bugsnag::Delivery::ThreadQueue Race Conditions

### ISSUE THREAD

**Issue by jturkel** [bugsnag/bugsnag-ruby#220]
The lazily initialization of `@queue` and `@worker_thread` in `Bugsnag::Delivery::ThreadQueue` doesn't appear to be threadsafe. We recently noticed exceptions that weren't reported to Bugsnag from a Puma process with 16 threads and this seems like a likely cause.

**Comment by ConradIrwin** [comment]
@jturkel Fixed in v2.8.2, thanks for reporting :).

**Comment by jturkel** [comment]
@ConradIrwin Thanks for the quick turnaround!
