### ISSUE TITLE
Calling Bugsnag.notify should log the success/result of the HTTP call

### ISSUE THREAD

**Issue by jeffblake** [bugsnag/bugsnag-ruby#223]
Currently, it will only log that it is sending the exception to Bugsnag.

It would be helpful, for debug purposes, to log the result of the HTTP call to Bugsnag.

**Comment by ConradIrwin** [comment]
Hey @jeffblake 

You can do this using the debug flag:
```
Bugsnag.configure do |config|
   ...
   config.debug = true;
end
```

Please let me know if you need more help.
