### ISSUE TITLE
Calling "exit 0" generates a Bugsnag event

### ISSUE THREAD

**Issue by dkhofer** [bugsnag/bugsnag-ruby#225]
Hello,

I'm with Fiksu.  We use Bugsnag for many of our projects.  I just set up a project with the 2.8.4 version of the gem and started seeing errors in Bugsnag from what appeared to be our scripts finishing normally.  It turns out that our script running system explicitly calls "exit 0" if a script finishes with no errors and "exit 1" otherwise.  Regardless of the status code, calling exit causes Ruby to raise a SystemExit error.  I believe this was causing the Bugsnag code to report errors.

I downgraded to 2.8.3 and the problem went away.  So I believe the 2.8.4 behavior is from this change: https://github.com/bugsnag/bugsnag-ruby/pull/221

It's possible to distinguish between a 0 exit code and something else by checking if success? is true, as in the following code:

-------------------------------
#!/usr/bin/env ruby

class Foo
  at_exit do
    if $!
      our_error = $!
      if our_error.respond_to?(:success?) && our_error.success?
      	puts "foo"
      else
        puts "bar"
      end
    end
  end
end

exit 0
-------------------------------

This prints out "foo".  If you change the exit to be "exit 1", it prints "bar" instead.

So in the at_exit code, would it be possible to check if the error is a SystemExit instance, and in that case only send a Bugsnag event if success? is false?

**Comment by dkhofer** [comment]
Argh, sorry for the crappy formatting, I should have previewed.

**Comment by jessicard** [comment]
Hey @dkhover - thanks for discovering this bug, sorry about that! We, by default, include `SystemExit` in our `DEFAULT_IGNORE_CLASSES`, (https://github.com/bugsnag/bugsnag-ruby/blob/0b3450a691513481711c33ea4849de6d5d25e8cb/lib/bugsnag/configuration.rb#L56) but it looks like that's not working. We're going to look into it :)

**Comment by dkhofer** [comment]
Great, thanks for the confirmation!  Let me know if you have any questions.

**Comment by jessicard** [comment]
Thanks @ConradIrwin!
