### ISSUE TITLE
ActionController::UnknownFormat should be a default ignored class.

### ISSUE THREAD

**Issue by ajoneil** [bugsnag/bugsnag-ruby#230]
This exception is thrown by rails when a request is made with the `Accept` header in a format incorrect for the controller - for example, a html request being made to a json only controller. In production, this is returned as a `406 Not Acceptable` response, and shouldn't show up in bugsnag.

**Comment by keeganlow** [comment]
Hey @ajoneil, if you don't want to see errors of this type, you can add the class to [ignore_classes](https://github.com/bugsnag/bugsnag-ruby#ignore_classes).

**Comment by vincentwoo** [comment]
Hi all,

I'm still seeing this error show up in bugsnag, using the latest version of the bugsnag library. Did something change recently?

**Comment by snmaynard** [comment]
We've made a change to the notifier to report all exceptions but with some exceptions being reported at a lower severity. Many people found it confusing/alarming that some exceptions were ignored by default. However you can edit the ignore classes configuration option to add this to the list to be ignored if you would like. Take a look at https://docs.bugsnag.com/platforms/ruby/rails/configuration-options/#ignore_classes for more details on that

**Comment by vincentwoo** [comment]
Is there a flag to say ignore errors reported at the "info" level instead? I'd rather not have to recreate the list by hand.

**Comment by snmaynard** [comment]
The list is at https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/middleware/classify_error.rb#L3

You can also write a before_notify function to ignore any errors that are reported at info level if you like.

You could probably do something like this (untested),

```ruby
Bugsnag.configure do |config|
  config.api_key = 'your-api-key-here'
  config.ignore_classes = Bugsnag::Middleware:: ClassifyError:: INFO_CLASSES
end
```
