### ISSUE TITLE
Ignored classes and caused by

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-ruby#232]
When an exception is wrapped by another, perhaps we should only check the outermost exception with respect to ignore_classes?

**Comment by snmaynard** [comment]
Closing this because its a broader issue than a single notifier

**Comment by tibbon** [comment]
Was this addressed in a larger sense elsewhere?

**Comment by snmaynard** [comment]
We ignore any classes if they appear in the ancestor chain of any of the exceptions raised (including caused by).

This errs on the side of not sending things through to us and if users want a different behaviour they can achieve that with custom code in a before notify callback. There are too many combinations to get a clear set of configuration options to achieve it.
