### ISSUE TITLE
ignored_classes is not threadsafe

### ISSUE THREAD

**Issue by mattcross** [bugsnag/bugsnag-ruby#237]
Under load on puma we sometimes see ignored exceptions reported to bugsnag.  I believe this line in configuration.rb may be the culprit.

```@ignore_classes.map! { |klass| klass.is_a?(Class) ? klass.name : klass }```

I have submitted #236 as a proposed fix.

**Comment by snmaynard** [comment]
This has been fixed - thanks @mattcross!
