### ISSUE TITLE
method_missing: undefined method `runner' 

### ISSUE THREAD

**Issue by jessiahr** [bugsnag/bugsnag-ruby#238]
When I add the bugsnag gem to my app I get this error:
```
gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing': undefined method `runner' for #<Bugsnag::Railtie:0x007f9a7d84b6f0> (NoMethodError)
```
 
Is there some additional configuration that I am missing?

**Comment by jessicard** [comment]
Hey @jessiahr - Sorry you're running into that. What version of ruby & rails are you on?

**Comment by jessiahr** [comment]
It looks like it is 1.9.3 and 3.2.13. It is an older app but I think it used to work in the past.
