### ISSUE TITLE
ignore_classes should be split for web context & background workers

### ISSUE THREAD

**Issue by kapso** [bugsnag/bugsnag-ruby#248]
Thats because the errors that should be on ignore list by default should not be on ignore list for background workers. For example `ActiveRecord::RecordNotFound` results in a 404 on a webapp, however in case of a background worker (e.g Sidekiq) it should report the exception to Bugsnag.

**Comment by trebor8x** [comment]
+1 for separate ignore lists
Searched for "Mongoid::Errors::DocumentNotFound" errors occuring in Sidekiq workers, but did not find them in Bugsnag.

**Comment by snmaynard** [comment]
I think adding an API for this is overly complex and pollutes the api. You can actually achieve this (credit @maletor) by doing something like,

```ruby
Bugsnag.configuration.ignore_classes.delete 'ActiveRecord::RecordNotFound'
Bugsnag.configuration.ignore_classes << lambda do |exception|
  Bugsnag.configuration.app_type == 'rails' &&
    exception.class == ActiveRecord::RecordNotFound
end
```

**Comment by jbescoyez** [comment]
@snmaynard How are we supposed to do that now that `ignore_classes` is deprecated and `discard_classes` does not support lambdas anymore? Tnx

**Comment by jbescoyez** [comment]
@snmaynard After digging a bit more, I found a solution:

```ruby
class ApplicationController < ActionController::Base
  before_bugsnag_notify :ignore_not_found

  private

  def ignore_not_found(report)
    report.ignore! if report.raw_exceptions.map(&:class).include?(ActiveRecord::RecordNotFound)
  end
end
  
```
