### ISSUE TITLE
Shoryuken middleware

### ISSUE THREAD

**Issue by michaeldiscala** [bugsnag/bugsnag-ruby#249]
Shoryuken is a background processing gem for amazon SQS  that is based on Sidekiq (see [here](https://github.com/phstc/shoryuken)). We have two applications that use it with Bugsnag, so I've written a middleware based on the Sidekiq implementation in this repo that reports errors from Shroyuken jobs. If I put together a pull request, would there be interest in shipping this middleware with bugsnag-ruby?

**Comment by snmaynard** [comment]
Yeah, it would be good to have that inside our gem!

Thanks @michaeldiscala!

**Comment by snmaynard** [comment]
@michaeldiscala do you have a copy of the middleware that you are using for this? Love to include it in the gem!

**Comment by kattrali** [comment]
Closing this one out, may revisit when I have time to hunt down the middleware.
