### ISSUE TITLE
Print more informative errors from Sidekiq integration

### ISSUE THREAD

**Issue by kattrali** [bugsnag/bugsnag-ruby#258]
Exceptions reported from Sidekiq are handled by [printing the queue of the current context](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/sidekiq.rb#L32), which can be less than informative. Improve the handling by exposing more information from the [`context_hash` parameter](https://github.com/mperham/sidekiq/wiki/Error-Handling#error-handlers).

**Comment by snmaynard** [comment]
Its actually worth noting that the args object is always an array of YAML strings so we can actually call `::YAML.load` on each one to actually print the arguments to the job. This is useful if there is anything binary in there (mongo ids for example)

**Comment by johanlunds** [comment]
Some ideas for better context-info:

* `my_job_class#perform`
* `sidekiq#my_job_class`
* `sidekiq/my_job_class#perform`
* `my_queue/my_job_class#perform`
* `my_queue#my_job_class`

I am leaning mostly towards to `my_job_class#perform`.

`app_type` is set to `sidekiq` either way, so it is possible to find all Sidekiq errors.

I might do a PR for this later.
