### ISSUE TITLE
Using Bugsnag v2.8.6, still not getting some Resque worker errors

### ISSUE THREAD

**Issue by sayem** [bugsnag/bugsnag-ruby#260]
Noticed there were some issues in the past with this (was reading https://github.com/bugsnag/bugsnag-ruby/issues/180 and https://github.com/bugsnag/bugsnag-ruby/issues/175).

I'm encountering the same thing sporadically though, sometimes exceptions from Resque workers are getting logged by Bugsnag and sometimes they aren't for some reason. 

Using Bugsnag 2.8.6, Resque 1.25.2, and Rails 4.1.11. 

And in config/initializers/resque.rb: 

```ruby
Resque::Failure::Multiple.classes = [Resque::Failure::Redis, Resque::Failure::Bugsnag]
Resque::Failure.backend = Resque::Failure::Multiple
```

Does that need to be changed to something else? Why isn't it always getting reported?

**Comment by sayem** [comment]
@ConradIrwin @loopj Also noticed this related SO answer, wonder if that's the issue: http://stackoverflow.com/a/30928280

**Comment by loopj** [comment]
This looks like it could be a likely cause - can you see if this helps with your particular issue and report back?

**Comment by sayem** [comment]
@loopj Yup will try it out and keep you posted - also if you guys have any other input please let us know.

**Comment by sayem** [comment]
@loopj Checking back - one of my coworkers noticed that those exceptions that weren't getting caught are actually listed in the default ignore classes (specifically, ActiveRecord::RecordNotFound) - https://github.com/bugsnag/bugsnag-ruby/issues/182

Made that update and it's catching those exceptions now, closing this. Thanks
