### ISSUE TITLE
rake bugsnag:heroku:add_deploy_hook fails on empty env vars

### ISSUE THREAD

**Issue by joelcogen** [bugsnag/bugsnag-ruby#261]
If you have an empty env var, it will output like this in `heroku config`:

    MY_VAR=

(reproduce with `heroku config:set MY_VAR=`).

`lib/bugsnag/tasks/bugsnag.rake:51` does this:

    k,v = c.split("=")
    obj[k] = v.strip.empty? ? nil : v

but the result of split in this case is `["MY_VAR"]`, so `v` is nil, and `strip` isn't defined on nil.

Maybe add:

    next if v.nil?

between the two lines, or change the test to

    obj[k] = (v.nil? || v.strip.empty?) ? nil : v

**Comment by kattrali** [comment]
Thanks for the report @joelcogen. Just pushed a fix, and will make a release soon.
