### ISSUE TITLE
Too easy to override params_filters defaults

### ISSUE THREAD

**Issue by bhelx** [bugsnag/bugsnag-ruby#264]
In the config object you allow setting some extra params filters via this API:

```ruby
config.params_filters += [
   'extraparam1',
   'extraparam2'
]
```

You also have some defaults that contain security related items:

https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/configuration.rb#L41

This is good, but it seems very easy to mistakenly overwrite them. The API gives you direct access to the `params_filters` Set. So a one character mistake means you will be leaking sensitive information:

 ```ruby
config.params_filters = [
   'extraparam1',
   'extraparam2'
]
```

Perhaps the API here can be slightly altered to disallow overriding security related defaults. I don't have any specific suggestions right now but wanted to open a discussion.

**Comment by kattrali** [comment]
Thanks for starting the discussion, @bhelx. There is certainly room for accidentally removing the defaults here. I'll need to give some thought to a potential fix. We could always append the default filters, for example.

**Comment by snmaynard** [comment]
It should still definitely be possible in my opinion - as sometimes people want to send fields containing those strings through to bugsnag - so a potential solution is to make it more explicit. Or we could potentially have a config setting to enable/disable default params filters.

**Comment by kattrali** [comment]
We could also make a (breaking) change and support separate methods on config, like `config.override_params_filters(array)` and `config.append_params_filters(array)`. It would be clearer at the expense of being more verbose.

**Comment by kattrali** [comment]
We are going to hold on this for now, though its worth noting for the next major release.. In the meantime, I'm updating the documentation to make this possibility clearer.
