### ISSUE TITLE
ignore_classes web context

### ISSUE THREAD

**Issue by maletor** [bugsnag/bugsnag-ruby#271]
Apologies for the new issue but GitHub hasn't allowed me to post a reply comment for two days now on this repository.

In theory this should work for #248.

```ruby
Bugsnag.configuration.ignore_classes.delete 'ActiveRecord::RecordNotFound'
Bugsnag.configuration.ignore_classes << lambda do |exception|
  Bugsnag.configuration.app_type != 'rails' &&
    exception.class == ActiveRecord::RecordNotFound
end
```

**Comment by snmaynard** [comment]
Thanks - I will post a comment on the issue at hand. I've no idea why github is preventing you from doing so!
