### ISSUE TITLE
Deploy notification fails due to "uninitialized constant Bugsnag::Configuration"

### ISSUE THREAD

**Issue by anderscarling** [bugsnag/bugsnag-ruby#272]
Bugsnag deploy notifications for capistrano seems to fail in my setup unless I explicitly add `require "bugsnag"` to my Capfile

My best guess is that this is due to something not being included since 5647d23f dropped the very same require line from `bugsnag/deploy.rb`.

Running on:
Capistrano Version: 3.4.0 (Rake Version: 10.5.0)

**Comment by kattrali** [comment]
Thank you for the detailed report, @anderscarling. Taking a look.

**Comment by dwradcliffe** [comment]
Same problem and same solution worked for me.

**Comment by kattrali** [comment]
Thanks for the confirmation, @dwradcliffe. I'm poking around for a fix which preserves the intent of https://github.com/bugsnag/bugsnag-ruby/pull/254 (failing JRuby for some reason), while not requiring the explicit import.

**Comment by kattrali** [comment]
Fixed by #275
