### ISSUE TITLE
Ignore classes not working

### ISSUE THREAD

**Issue by SergeyKishenin** [bugsnag/bugsnag-ruby#280]
I have Bugsnag configured like:

```
Bugsnag.configure do |config|
  config.api_key = "secret"
  config.notify_release_stages = ["production", "staging"]
  config.params_filters = ["password", "password_confirmation", "number", "verification_value"]
  config.ignore_classes << "CustomErrors::RestartDelayedJob"
end
```

I have `CustomErrors::RestartDelayedJob` set to be ignored but I can still see it reported in Bugsnag. This error raised intentionally in background jobs only.

Gem version is 2.8.13.

**Comment by mlhamel** [comment]
Same here. ignore_classes doesn't seems work

**Comment by mlhamel** [comment]
My bad, make sure to call `notify_or_ignore` and not `notify` only. I know that's weird.

**Comment by mlhamel** [comment]
Sadly still with `notify_or_ignore` it doesn't work

**Comment by snmaynard** [comment]
I'm planning on tweaking some of the ignore classes interfaces in a v5 rewrite coming soon. I am also proposing that we drop the `notify_or_ignore` method in the short term to try to make the ignore functionality more predictable. See #319 for more information.

**Comment by SergeyKishenin** [comment]
@snmaynard Looks like the issue is not reproducing anymore. Closing

**Comment by nicolaslupien** [comment]
This problem is occurring in the latest version (5.3.3). I'm not able to reproduce the steps but sometime an ignored class shows up in bugsnag

**Comment by snmaynard** [comment]
Can you contact support@bugsnag.com with a link to an error that should be ignored and your configured ignore classes? That will probably help us track this down.
