### ISSUE TITLE
Silence the ready message

### ISSUE THREAD

**Issue by csuhta** [bugsnag/bugsnag-ruby#283]
I have this config for a Rails app and `bugsnag` 3.0.0:

```ruby
Bugsnag.configure do |config|
  config.api_key = ENV.fetch("BUGSNAG_API_KEY")
  config.app_type = "rails"
  config.notify_release_stages = ["production"]
  config.send_environment = true
  config.use_ssl = true
end
```

Bugsnag prints this message for everything the Rails app does (boot, `rake`, `rails`, migrations, test suite, etc):

```
** [Bugsnag] Bugsnag exception handler 3.0.0 ready, api_key=[snip]
```

We want bug capture for production rake tasks, but we don't want this message in the logs every single time the Rails app initializes, especially since it contains the API key. Is there some way to silence this message?

**Comment by kattrali** [comment]
Thanks for the report, @csuhta. I updated the ready message to remove the API key. The message is displayed at the `info` log level, could the logging level potentially be turned up for running tests, etc?

**Comment by csuhta** [comment]
Would you explain the proper way to turn up the logging level or silence Bugsnag when `BUGSNAG_API_KEY` is set in the environment?

The gem auto-configures itself from the environment on when it gets `require`-ed. You don't have an opportunity to silence it from a Rails initializer.

Here's an example:
```ruby
# config/initializers/bugsnag.rb
puts "Bugsnag initializer reached"
Bugsnag.configure do |config|
  config.logger = Logger.new("/dev/null")
  config.api_key = ENV.fetch("BUGSNAG_API_KEY")
  config.app_type = "rails"
  config.notify_release_stages = ["production"]
  config.send_environment = true
  config.use_ssl = true
end
```

But the message gets logged before you can configure Bugsnag:

```
$ rails c
** [Bugsnag] Bugsnag exception handler 5.0.0 ready
Bugsnag initializer reached
Loading development environment (Rails 5.0.0.1)
```
