### ISSUE TITLE
app_type is not correctly set on sidekiq integration

### ISSUE THREAD

**Issue by Draiken** [bugsnag/bugsnag-ruby#285]
Hi there, I suspect `Bugsnag::Railtie` class is overriding the `app_type` to `rails` even when the sidekiq integration is loaded. Since the type is set before initialization it means rails is already loaded, so sidekiq's integration had already set the type.

Since sidekiq normally is used alongside rails, I believe this is a bug.

Happy to submit a patch if it is indeed a bug

**Comment by kattrali** [comment]
Thank you for the report, @Draiken! This is definitely a regression and a patch would be welcome.
