### ISSUE TITLE
Encoding issue with request pathname and non-ascii characters

### ISSUE THREAD

**Issue by eanakashima** [bugsnag/bugsnag-ruby#297]
It seems that in certain cases, non-ascii characters in request url params can cause the request pathname to not display as part of the `url` field in the Event > Request tab of the Bugsnag UI. Instead, you see only the protocol and hostname. I'll update with steps to reproduce if I can find a good test case.

**Comment by snmaynard** [comment]
@eanakashima did you manage to get an example case together? We have relatively good utf sanitisation in https://github.com/bugsnag/bugsnag-ruby/blob/16178f54cac8bd6dcbe27c1903c362c58d192774/lib/bugsnag/cleaner.rb which should handle most cases - but would be good to know if something can sneak through!

**Comment by eanakashima** [comment]
@snmaynard No. I believe this was originally reported in via support, and I haven't heard a similar report since. I think we can call this closed for now.
