### ISSUE TITLE
rails_admin error not showing up

### ISSUE THREAD

**Issue by arthurnn** [bugsnag/bugsnag-ruby#300]
### Problem

I have an error on a rails_admin view inside my app. However the error is not been sent to Bugsnag.
Here is the logs: https://gist.github.com/arthurnn/8d17e2c75fc9fa9d34758bce630af0b7
I wonder if this is happening because the stack has no reference to my application code, as it is happening inside rails_admin.

cc @kattrali , I think we talked about that over rails conf.

**Comment by kattrali** [comment]
Thank you for following up, @arthurnn! I'm taking a look to ensure we aren't dropping the ball on our end, though I might have some additional questions in a bit.

**Comment by snmaynard** [comment]
Hey @arthurnn apologies for the delay here. The reasons that I can think about off the top of my head are `ignore_classes`, `notify_release_stages` or something in the chain before bugsnag rescuing the exception. Is there anything in the log that suggests bugsnag was attempting to send the exception? 

Editing the bugsnag [rack middleware](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/rack.rb#L34) to see if an exception makes it into our rescue block would also help diagnose whether its getting to us or not.

**Comment by arthurnn** [comment]
Hey @snmaynard this is what I see on logs:
```
I, [2016-08-20T22:15:56.536489 #24551]  INFO -- : ** [Bugsnag] Notifying https://notify.bugsnag.com of I18n::ArgumentError from api_key xxxxxxxxx
F, [2016-08-20T22:15:56.805335 #24551] FATAL -- :
ActionView::Template::Error (Object must be a Date, DateTime or Time object. "" given.):
     96:             - if @other_left_link ||= other_left && index_path(params.except('set').merge(params[:set].to_i != 1 ? {set: (params[:set].to_i - 1)} : {}))
     97:               %td.other.left= link_to "...", @other_left_link, class: 'pjax'
     98:             - properties.map{ |property| property.bind(:object, object) }.each do |property|
     99:               - value = property.pretty_value
    100:               %td{class: "#{property.css_class} #{property.type_css_class}", title: strip_tags(value.to_s)}= value
    101:             - if @other_right_link ||= other_right && index_path(params.merge(set: (params[:set].to_i + 1)))
    102:               %td.other.right= link_to "...", @other_right_link, class: 'pjax'
  i18n (0.7.0) lib/i18n/backend/base.rb:53:in `localize'
  i18n (0.7.0) lib/i18n.rb:247:in `localize'
  rails_admin (0.8.1) lib/rails_admin/config/fields/types/datetime.rb:65:in `block in <class:Datetime>'
```
Also, I added some `Bugsnag.log` to the rack middleware to see if it was getting into that rescue block, and it was indeed. So I am think we are dispatching the error to bugsnag.
However, I don't see the error there.

**Comment by Cawllec** [comment]
Closing this one down, will continue conversation in #353
