### ISSUE TITLE
Add `ActionDispatch::ParamsParser::ParseError` to ignore_classes

### ISSUE THREAD

**Issue by tjwp** [bugsnag/bugsnag-ruby#302]
Should `ActionDispatch::ParamsParser::ParseError` also be included as part of the default `ignore_classes`?

**Comment by kattrali** [comment]
That's a good question, @tjwp! I can think of a few cases for and against completely discarding invalid parameter errors, so it might be good for a few days of discussion.

**Comment by snmaynard** [comment]
I think adding things to default ignore classes can be a very confusing thing and potentially hide legitimate errors so I am trying to transition away from having too many things in there and making it easy for people to have their own ignore_classes that they have opted into and understand the consequences of.

Thanks for the suggestion though - I think in many apps ignoring this could be a good idea. Perhaps we can add it as a suggested class to ignore in the documentation with an explanation of when that would be raised.
