### ISSUE TITLE
alias_method_chain is deprecated in Rails5

### ISSUE THREAD

**Issue by philippfrank** [bugsnag/bugsnag-ruby#303]
See: https://github.com/rails/rails/blob/5-0-stable/activesupport/CHANGELOG.md

Used in `lib/bugsnag/rails/action_controller_rescue.rb`.

**Comment by kattrali** [comment]
Thank you for the report, @philippfrank. The contents of `action_controller_rescue` are exclusively legacy Rails 2 extensions which should have no effect on newer versions, and I added a check to enforce this behavior in 130ba926e7b051b98926b12cd6e4bcd7b5cb732c.
