### ISSUE TITLE
Default values for ignore_classes don't suit background worker/rake contexts

### ISSUE THREAD

**Issue by s-andringa** [bugsnag/bugsnag-ruby#304]
Most of the errors that are ignored by default are specific to a webserver context, and should often not be ignored when raised from a background worker or a scheduled rake task. Especially `ActiveRecord::RecordNotFound` and `Mongoid::Errors::DocumentNotFound` can cause problems, as it is not uncommon for them to occur outside of a webserver context.

Currently one would have to resort to something like this:

``` rb
Bugsnag.configure do |config|
  # Ignore fewer errors than default (which includes webserver specific entries such as AR:RecordNotFound):
  config.ignore_classes = ["SignalException", "SystemExit"] if background_worker? || rake_task?
end
```

The value for `#background_worker?` is not always easily determined. This could easily lead to unnecessary complex setup for anyone using a background worker or scheduling rake tasks. I think many Bugsnag users do, so lets make their lives a little easier!

One quick (but dirty) solution could be to have background worker and rake integrations use a separate setting, e.g. respectively `config.background_worker_ignore_classes` and `config.rake_ignore_classes`.

Cheers.

**Comment by snmaynard** [comment]
The ruby notifier actually has `app_type` detection already so you could do something like,

```ruby
config.ignore_classes << lambda  do |ex|
  if Bugsnag.configuration.app_typ == "rails"
    ex.is_a? SignalException
  else
    false
  end
end
```

We could add some documentation around it. Its hard to detect all the different background_workers etc so this might be a good way of making it generic and allowing people to do what they want easily.

What do people think of just improving the docs in this area with an example?

**Comment by s-andringa** [comment]
Thanks @snmaynard. I like that approach better. It makes it less of a hassle to get around the issue. If I had seen this in the docs I would have probably solved it this way. So, yes, improving the docs would definitely be a step forward.

**Comment by PragTob** [comment]
I can see what you wanted to achieve with these default ignore classes, but that is very surprising in a number of contexts and lets people miss important errors. Not sure if one should even reconsider these defaults, especially with `ActiveRecord::NotFound`. A documentation fix would be appreciated and needed either way though :)

**Comment by troex** [comment]
My rake tasks was failing because of load error `NameError` (class called with wrong name). Bugsnag didn't report it unless I added `require 'bugsnag/rake'` into my Rakefile.

Expected it to work out-of-the-box. My app is Sintra app with plain ruby rake tasks.

**Comment by Cawllec** [comment]
We've moved the ignore classes into a middleware that gives them a severity of `info` rather than suppressing them.  The default behaviour is now to report all exceptions and errors.
