### ISSUE TITLE
Bugsnag.clear_request_data not called after Sidekiq worker runs for Sidekiq versions >= 3

### ISSUE THREAD

**Issue by tmak** [bugsnag/bugsnag-ruby#306]
Maybe I'm missing something here.
For Sidekiq versions >= `3` the middleware [`Bugsnag::Sidekiq`](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/sidekiq.rb#L4) is not used and because of that [`Bugsnag.clear_request_data`](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/sidekiq.rb#L17) is not called after Sidekiq worker runs.

I'm happy to create a PR if somebody else confirms this as a bug.

**Comment by martin308** [comment]
Hi @tmak, as we don't call `set_request_data` in the code path when sidekiq version is >= 3 there is no need to call `clear_request_data` as the middleware does.

**Comment by snmaynard** [comment]
I have just merged in a fix for this in #317 - will get a release out for it soon
