### ISSUE TITLE
Better error context for Sidekiq

### ISSUE THREAD

**Issue by sandstrom** [bugsnag/bugsnag-ruby#309]
This commit adds the class: https://github.com/bugsnag/bugsnag-ruby/commit/9d79c9f4698dcafbb28d5c1af139b97d8a6d058d

However, it's just *ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper* in Bugsnag (not very useful):

![image](https://cloud.githubusercontent.com/assets/122287/17546349/f717eede-5ee1-11e6-930b-75a0b6e3326c.png)

Instead I'd suggest using the `wrapper` value (which is shown in the Sidekiq tab). This will be something like `MyQuickJob` which is much more useful.

**Comment by kattrali** [comment]
Hi @sandstrom, thanks for the feedback. That's a good idea. I was thinking that class name was something more useful, but perhaps the wrapper makes more sense.

**Comment by sandstrom** [comment]
@kattrali The class name never change, for all our errors it always says `ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper` instead of the ActiveJob class.

**Comment by snmaynard** [comment]
Just got a fix for this in #317 - will get a release out soon

**Comment by sandstrom** [comment]
@snmaynard Awesome! ⛵  When will you release a new version?

**Comment by snmaynard** [comment]
Planning on a release early next week - probably Monday or Tuesday. A few more things I want to try and get in to it.

**Comment by sandstrom** [comment]
@snmaynard much thanks

**Comment by sandstrom** [comment]
@snmaynard We've deployed 5.0 and still seeing this. Have I misunderstood something or is the issue still around?

*(expected the context value, to the right of the bold error class to be the name of the job)*

![image](https://cloud.githubusercontent.com/assets/122287/18045387/e396df00-6dd2-11e6-9ab3-dc12a673b33c.png)

**Comment by sandstrom** [comment]
@snmaynard friendly ping 😄

**Comment by snmaynard** [comment]
#323 should be the fix for this - we should be using `wrapped` not `wrapper` for the active job class name

**Comment by kattrali** [comment]
Closed via #323.
