### ISSUE TITLE
Shoryuken middleware

### ISSUE THREAD

**Issue by nigelramsay** [bugsnag/bugsnag-ruby#322]
After seeing the original Shoryuken issue/question (https://github.com/bugsnag/bugsnag-ruby/issues/249), and also wanting to use Shoryuken with Bugsnag - I have gone and cloned the Sidekiq middleware to work with Shoryuken. 

I'm happy to create a PR, but might need a little feedback/assistance. 

Shall I?

**Comment by kattrali** [comment]
@nigelramsay That sounds great! Feel free to make a PR and include any questions/concerns, and we’ll assist where needed. There’s some larger changes landed in [v6](https://github.com/bugsnag/bugsnag-ruby/pull/320), but this would be good regardless.

**Comment by nigelramsay** [comment]
@kattrali I have created the PR as requested https://github.com/bugsnag/bugsnag-ruby/pull/324
