### ISSUE TITLE
Return Bugsnag ID and report URL in Bugsnag.notify

### ISSUE THREAD

**Issue by Nowaker** [bugsnag/bugsnag-ruby#325]
There're various kinds of errors. Less important and more important. If there's a failure in the code that handles a payment, that's the most important type of error you might have. Whenever there's an error like that, our app reports it explicitly to Bugsnag and also sends a Slack notification. It'd be really good to attach the Bugsnag ID and URL to that Slack notification so we don't have to look for this exception manually in Bugsnag. With a URL we can hop straight into this very exception in this very environment.

Currently, `Bugsnag.notify` returns the notification itself. Delivery may be performed in a separate thread or inline, depending on `Bugsnag::Delivery`'s strategy. There're are two strategies for delivery - `Synchronous` or `ThreadQueue`. The feature I'm proposing is extremely easy to do on the code level for the former, and a little more complicated for the later (which appears to be the default).

On the backend side, Bugsnag needs to return a JSON response instead of just "OK" as body. `http.request(request)` in https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/delivery/synchronous.rb#L40 And then store it on Notification object, e.g. `notification.bugsnag_id` and `.bugsnag_url` or something like that.

```
notif = Bugsnag.notify_or_ignore e
puts notif.bugsnag_url # => https://app.bugsnag.com/ORG/PROJ/errors/ID
```

In async call situation, these would be null. A callback could be passed instead:

```
Bugsnag.notify_or_ignore e do |notif|
  notif.bugsnag_url # => https://app.bugsnag.com/ORG/PROJ/errors/ID
end
```

**Comment by kattrali** [comment]
Thank you for the report and suggestions, @Nowaker. We could probably in the future have a post-request callback for both the synchronous and asynchronous cases. I’ll forward the ideas along to the backend team, as it would require the server component to first support sending a unique identifier of some sort.

**Comment by Nowaker** [comment]
Thanks @kattrali. An alternative approach is to assign a UUID generated via
`SecureRandom.uuid` to the notification that the backend would accept if
it's unique on project scope. (And UUIDs should be unique no matter what)
This way the client can send stuff to Bugsnag and doesn't have to wait for
response or webhook.

**Comment by jordan-brough** [comment]
Any hope of this happening?

Rollbar does this and it's very handy.
Here:
https://github.com/rollbar/rollbar-gem/blob/v2.15.5/lib/rollbar/notifier.rb#L682-L687
and here:
https://github.com/rollbar/rollbar-gem/blob/v2.15.5/lib/rollbar/item.rb#L89

**Comment by Cawllec** [comment]
As this goes a bit beyond the Ruby notifier I've passed this up to our prioritisation group.

I'll update this issue with more information when I know it.
