### ISSUE TITLE
Extend ignore_classes examples

### ISSUE THREAD

**Issue by charlieegan3** [bugsnag/bugsnag-ruby#328]
In the [docs for ignoring classes](https://docs.bugsnag.com/platforms/ruby/rails/configuration-options/#ignore_classes) it'd be useful have an example of a string being used too (as they are [in the tests](https://github.com/bugsnag/bugsnag-ruby/blob/42552a894bb2f70fd48df8b6bc9d3e3da7ba11aa/spec/notification_spec.rb#L590), for example).

As the error class may not have been loaded when the initializer runs, it feels like this is a feature that's not being fully 'advertised' in the docs.

Cheers

**Comment by Cawllec** [comment]
Hi @charlieegan3, `ignore_classes` no longer accepts strings, only classes, so I'll close this one down.
