### ISSUE TITLE
ignore_classes support for modules

### ISSUE THREAD

**Issue by jturkel** [bugsnag/bugsnag-ruby#336]
It would be great if the `ignore_classes` infrastructure considered modules included in the exception's class and singleton class e.g.

```
Bugsnag.configure do |config|
  # Ignore any exceptions that include the ExceptionReporting::IgnorableError module
  config.ignore_classes << ExceptionReporting::IgnorableError
end

...

begin
  do_something!
rescue MyException => e
  # We generally want to report MyExceptions to Bugsnag but not in this particular case.
  # However we still want to re-raise the exception so things like Delayed Job failure handling
  # will kick in.
  raise e.extend(ExceptionReporting::IgnorableError)
end
```
The workaround is to use the proc form of ignore_classes:
```
Bugsnag.configure do |config|
  config.ignore_classes << Proc.new do |exception|
    exception.is_a?(ExceptionReporter::IgnorableError)
  end
end
```

**Comment by kattrali** [comment]
That's a creative solution to the problem 🤔 
I think we've a lot of complexity when it comes to `ignore_classes` and customization which would best be served by adding a more generic mechanism to configuration to allow users to edit (and cancel) error reports. Its something we support on other platforms now, and are working towards for the next major version, which will be completed in the near future.
