### ISSUE TITLE
Is v5.0.2 actually out yet?

### ISSUE THREAD

**Issue by atyndall** [bugsnag/bugsnag-ruby#341]
The changelog suggests it came out on 14 Nov 2016, but there is no v5.0.2 tag on the repo, nor is 5.0.2 available on rubygems.org?

Thanks for any clarification!

**Comment by kattrali** [comment]
Thanks for the report, @atyndall. I'm not sure what happened here. However, I updated the changelog and pushed a new release as v5.1.0, since the changeset had some enhancements. It should be all good now!
