### ISSUE TITLE
NoMethodError: undefined method `configure' for Bugsnag:Module

### ISSUE THREAD

**Issue by faucct** [bugsnag/bugsnag-ruby#343]
Hello. [This code](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/railtie.rb#L28) can be executed during the [file evaluation](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag.rb#L17) before the `Bugsnag.configure` method is [defined](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag.rb#L35). If the rails application is already defined when you require `bugsnag`.
I have noticed this behaviour in specs while requiring gem after the dummy app definition. I am not sure if this is your issue and an issue at all, just thought you should know.

**Comment by faucct** [comment]
Thanks.

**Comment by kattrali** [comment]
No problem! Releasing shortly.
