### ISSUE TITLE
Notification is not sent in rails console

### ISSUE THREAD

**Issue by peco8** [bugsnag/bugsnag-ruby#348]
This is not a technical issue.

I've set up Bugsnag in development/production environment in Rails 4.

I'd love to test thing out in rails console.

```
Bugsnag.notify('test test test')
```
And I also tried
```
Bugsnag.notify(RuntimeError.new("oops"))
```
The config is following.

```
  Bugsnag.configure do |config|
    config.api_key = ENV['BUGSNAG_SECRET']
    config.notify_release_stages = ["production", "development"]
  end
```

Am I missing something important?

**Comment by kattrali** [comment]
Thanks for the report, @peco8. Is `BUGSNAG_SECRET` set? Do any errors appear on your Bugsnag dashboard?

**Comment by Cawllec** [comment]
I'm closing this for now, if the issue happens again or if you have any more information let us know.
