### ISSUE TITLE
App Type is ignored when running rake tasks on a rails app.

### ISSUE THREAD

**Issue by zee-roostify** [bugsnag/bugsnag-ruby#351]
Consider the following scenario:
```
Given a brand spanking new Rails app with bugsnag configured with `app_type="service-a"`
When I run `bin/rake bugsnag:test_exception`
Then I receive an exception with an app_type of `rake`
Instead I would like to receive an exception with the app_type of `service-a`
```

When looking at the rack middleware, I noticed that [it used an `||=` to set the app_type](https://github.com/bugsnag/bugsnag-ruby/blob/v5.2.0/lib/bugsnag/rack.rb#L25); which seems reasonable.  However on rake, it [always sets the app_type to `rake`](https://github.com/bugsnag/bugsnag-ruby/blob/v5.2.0/lib/bugsnag/rake.rb#L8)

Because we have a service oriented architecture, we were planning to use the `app_type` to distinguish between the many different services in our deployments, (`mailer-api`, `mailer-worker`, `mailer-rake`) so that all exceptions stream in to the same project and can be filtered/explored/acted upon in this manner.

**Comment by zee-roostify** [comment]
Whoops. Hit enter and it submitted before I filled out. One moment!

**Comment by kattrali** [comment]
Thanks for the detailed report, @zee-roostify. This makes a lot of sense! Scheduling this in as an enhancement.
