### ISSUE TITLE
Bugsnag breaks Jbuilder on rails 5

### ISSUE THREAD

**Issue by glitch003** [bugsnag/bugsnag-ruby#352]
Hi, I'm running into an issue where Bugsnag is breaking jbuilder on rails 5.  More info is here: https://github.com/rails/jbuilder/issues/346

**Comment by kattrali** [comment]
Thanks for the report, @glitch003. This should be fixed as of #338. Are you running v5.2.0?

**Comment by kattrali** [comment]
Closing, as this should have been fixed in v5.2.0
