### ISSUE TITLE
NameError not getting into bugsnag

### ISSUE THREAD

**Issue by arthurnn** [bugsnag/bugsnag-ruby#353]
Hi, We had a problem in our app, that one request was returning a 500 to the client. After checking the logs, i found the following:

```
INFO -- : ** [Bugsnag] Notifying https://notify.bugsnag.com of NameError from api_key XXXX
ActionView::Template::Error (wrong constant name professional):
```

However, for some reason, the error never got to bugsnag. While some, other errors are getting there. Not sure what the problem is, and how to debug it.

**Comment by Cawllec** [comment]
Hi arthurnn, sorry for taking so long to respond.  Are you still seeing this issue occur?

**Comment by arthurnn** [comment]
I dunno TBH.
We fixed the issue in our app, which was legit. However, the entire problem here is that bugsnag was not catching that error. I am not sure why.

**Comment by kattrali** [comment]
Thanks, @arthurnn. We recently finished a fairly large overhaul which tidied up a lot of the internals as well as adding a number of small fixes. Let us know if it happens again, but in the meantime I'll mark this as resolved.
