### ISSUE TITLE
Can you expand on why certain classes are ignored?

### ISSUE THREAD

**Issue by meagar** [bugsnag/bugsnag-ruby#360]
We've discovered the [large set of ignored exceptions](https://github.com/bugsnag/bugsnag-ruby/blob/1aee48084f798dd4cc69e11fd9a9ac0ae208a084/lib/bugsnag/configuration.rb#L48) are swallowing some exceptions that we would very much like to hear about.

Some of these seem like exceptions that *most* people would want to know about, such as:
- `AbstractController::ActionNotFound` one of my routes leads to an action I didn't find, I'd like to know about this
- `ActionController::InvalidAuthenticityToken` if 90% of my users start seeing this error, I need to know about it
- `ActionController::ParameterMissing` My front-end code and back-end code are out of sync, and my tests miss a code path, I need to know this
- `ActiveRecord::RecordNotFound` if I use a `find!` to trigger an exception, I expect to be told when that find returns no records, *especially* if I manually `Bugsnag.notify(...)` the exception in a `rescue`

Can you expand in the documentation *why* these errors are the default set? As it stands I plan to reduce `ignore_classes` to `[]` so that *all* errors start showing up, but it would be useful to know why this set wound up containing all the things it contains.

**Comment by FeminismIsAwesome** [comment]
+1 on this. There was an error that caused a template to blow up from an ActiveRecord::RecordNotFound, and I was hoping to have been notified by bugsnag instead of it being ignored. The ignore list caught me by surprise.

**Comment by kattrali** [comment]
The answer seems to be somewhat lost to the mist. Going forward we shouldn't have these as defaults. It would be a breaking change to rethink this, but moving this kind of configuration into an option or a deliberate choice in a `before_notify` callback would prevent confusion.

**Comment by Cawllec** [comment]
We've moved all of the pre-existing ignore classes into a middleware that now marks them as `info` severity, meaning the default behaviour should be to report all errors and exceptions.
