### ISSUE TITLE
Missing docs: exception.bugsnag_meta_data

### ISSUE THREAD

**Issue by macobo** [bugsnag/bugsnag-ruby#365]
This gem has undocumented way of adding tabs to exceptions which I found really useful and think deserves spotlight in official documentation.

Namely, you can create an `bugsnag_meta_data` method on any exception object, which will be used by bugsnag to create additional tabs, similar to how `#add_tab` works. This comes in handy in situations where `Bugsnag.notify` is called automatically, for example when using `delayed_job`.

Example:
```ruby
class MyCustomError < StandardError
  attr_reader :metadata
  def initialize(message, metadata)
    super(message)
    @metadata = metadata
  end
 
  def bugsnag_meta_data
    {tabname: metadata}
  end
end

Bugsnag.notify(MyCustomError.new("Error message", value1: '1', value2: {nested: 3}))
```

Will create a tab named `tabname` with `value1` and `value2` listed in it.

**Comment by kattrali** [comment]
Thanks for the report, @macobo! That's definitely something we should document.

**Comment by Cawllec** [comment]
Hi  @macobo, we've added some documentation for customising error reports as you've described that can be found [here](https://docs.bugsnag.com/platforms/ruby/other/customizing-error-reports/#custom-error-diagnostic-data)!

**Comment by macobo** [comment]
Perfect, thank you! :+1:
