### ISSUE TITLE
Add backtrace cleaner support

### ISSUE THREAD

**Issue by sobrinho** [bugsnag/bugsnag-ruby#384]
### Expected behavior
Would be nice to have a backtrace cleaner to clean up some app internal backtrace, like this:

```ruby
Bugsnag.add_backtrace_cleaner /error_handler_service\.rb/
```

In that way, we wouldn't see our service object in the backtrace, which isn't relevant.

### Observed behavior
N/A

### Steps to reproduce
N/A

### Version
5.4.1

### Additional information
Ruby client, Rails app

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by kattrali** [comment]
Thanks for the report, @sobrinho.

It sounds like this behavior is a good candidate for using [`before_notify_callbacks`](https://docs.bugsnag.com/platforms/ruby/customizing-error-reports/#adding-callbacks), which are blocks invoked on error reports prior to delivery. Each `report` contains a list of `exceptions`, which can be modified:

```ruby
Bugsnag.before_notify_callbacks << lambda {|report|
  # iterate over each exception, or grab just the top one, if that makes more sense
  report.exceptions.each do |exception|
    # filter the frames from the error handler
    exception.backtrace.reject! {|frame| frame =~ /error_handler_service\.rb/ }
  end
}
```
