### ISSUE TITLE
Difficulty configuring Bugsnag in Rails before it configures itself

### ISSUE THREAD

**Issue by csuhta** [bugsnag/bugsnag-ruby#391]
Here's an example initializer in Rails:

``` ruby
# config/initializers/bugsnag.rb
puts "Bugsnag initializer reached"
Bugsnag.configure do |config|
  config.logger = Logger.new("/dev/null")
  config.api_key = ENV.fetch("BUGSNAG_API_KEY")
end
```

The Bugsnag ready message gets logged before this initializer runs:

```
$ rails c
** [Bugsnag] Bugsnag exception handler 5.5.0 ready
Bugsnag initializer reached
Loading development environment (Rails 5.1.4)
```

I want to change the Bugsnag logger and/or explicitly configure Bugsnag myself. I do not want the gem to try to automatically detect its own configuration. What is the correct way to do this in Rails and other Ruby environments when using Gemfiles/Rubygems to load this gem?

**Comment by Cawllec** [comment]
So at the moment there isn't a way to do that in several of supported framework.  We're automatically requiring the framework integrations which can trigger off configuration options, such as the `railtie` integration for rails.

While there's no way to disable this at the moment, if this is requested it's something we could look into adding in the future.

**Comment by kattrali** [comment]
@csuhta Can you provide some examples of the kinds of configuration you'd like to change up front? Perhaps there are specific options we could provide or options we can better surface in the documentation.

**Comment by csuhta** [comment]
@kattrali For our use case: We have a lot of nighty/hourly sync processes and rake tasks. I would like to override the Bugsnag logger object to point to a custom logger and sometimes also want to completely silence the gem, including the `Bugsnag exception handler X ready` message

**Comment by kattrali** [comment]
Gotcha. That makes a lot of sense. We could potentially support an environment variable (e.g. `BUGSNAG_AUTOLOAD` or similar) to disable loading extensions though afterwards you'd need to load them manually. Does that approach make sense?

**Comment by csuhta** [comment]
@kattrali That would be perfect. I'm happy to configure the gem myself if I can cleanly wrest automatic behavior away from it.

**Comment by cookrn** [comment]
We're currently noticing similar behavior where the Railtie `before_initialize` runs prior to our Bugsnag initializer which sets the API key. This means on every boot of a non-development environment we see the `No valid API key has been set, notifications will not be sent` message.

**Comment by RobertoSchneiders** [comment]
@cookrn We're having the same problem.

**Comment by ifightcrime** [comment]
@cookrn @RobertoSchneiders my fix for now is to just set the key in advance as the environment variable `BUGSNAG_API_KEY`.

https://github.com/bugsnag/bugsnag-ruby/blob/7336834095ee0b0287f827f0be1f9a53023e4323/lib/bugsnag/configuration.rb#L76

**Comment by jfelchner** [comment]
@kattrali why did this issue get closed?

**Comment by csuhta** [comment]
@jfelchner It's now possible to set `BUGSNAG_DISABLE_AUTOCONFIGURE` in your environment to prevent the gem from configuring itself when it's `required`. See the PR here: https://github.com/bugsnag/bugsnag-ruby/pull/419

**Comment by jfelchner** [comment]
@csuhta I don't want to disable autoconfiguration, I just don't want a warning telling me that my API key is not valid when I'm setting my API key in the initializer.

**Comment by jfelchner** [comment]
Can we reopen this issue until this gets fixed?

**Comment by snmaynard** [comment]
I've reopened this one as a matter of course, but it looks to me like the issue is solved and you are experiencing something else @jfelchner. You are seeing bugsnag log that the api key is invalid, but it's correct? That would be a different issue worth raising a separate issue for to make sure it doesnt get lost. If

**Comment by jfelchner** [comment]
@snmaynard it's basically the same issue as this whereby Bugsnag is initializing itself before the point in the Rails boot process where Rails reads the `Bugsnag` configuration block.

**Comment by jfelchner** [comment]
Also for some more clarification, if I move the `Bugsnag` configuration block with the API key in it to the top of my `application.rb`, no error.  Top of my `environments/development.rb`? No error.  `config/initializers/bugsnag.rb`?  Error.  `config/initializers/00_bugsnag.rb`  Error.

**Comment by pbougie** [comment]
I'm also experiencing problems configuring Bugsnag in a Rails initializer. Setting the API key there does nothing. It has to be done earlier. The opening example is misleading:

```ruby
# config/initializers/bugsnag.rb
Bugsnag.configure do |config|
  config.api_key = ENV.fetch("BUGSNAG_API_KEY")
  ...
end
```

The API key is not being set here. Rather it's using ENV["BUGSNAG_API_KEY"] directly when Bugsnag is loaded.

I'm currently using Rails 5.2 RC2 with the new Credentials feature (I'm moving away from using ENV variables for atomic deploys). I tried the following:

```ruby
# config/initializers/bugsnag.rb
Bugsnag.configure do |config|
  config.api_key = Rails.application.credentials.bugsnag_api_key
end
```

This unfortunately does not work because the initializer is executed too late. I get the following warning with this configuration: `"No valid API key has been set, notifications will not be sent"`.

If I move the same configuration to `application.rb`, it begins working, e.g.:

```ruby
# config/application.rb
Bugsnag.configure do |config|
  config.api_key = Rails.application.credentials.bugsnag_api_key
end
```

The rest of the configuration can be set in `config/initializers/bugsnag.rb`. Does not make for a clean implementation.

**Comment by jfelchner** [comment]
As per my comment here: https://github.com/bugsnag/bugsnag-ruby/issues/438#issuecomment-377124355  can we reopen this until it is adequately fixed?

**Comment by Cawllec** [comment]
@jfelchner a change has been made into how the API key validity is logged, which will be released shortly.  This will fix the issues as noted here.
