### ISSUE TITLE
Bring back vendor paths

### ISSUE THREAD

**Issue by etiennebarrie** [bugsnag/bugsnag-ruby#394]
Before v6.0, Bugsnag was annotating each line of the backtrace, setting `inProject` to `false` if the file was not in the project root, or if it was in one of the vendor paths, which defaulted to directories named `vendor`.

I think this feature should be brought back, because when you use `bundle install --deployment`, by default it installs the gems inside the project, under `vendor/bundle`. 

### Expected behavior
* I expect to only see my code when I look at an error or event on Bugsnag, not the framework's code or gems.
* If I need to, I can show the full trace.

### Observed behavior
* All lines of the backtrace end up showing on the dashboard.
* It seems the grouping algorithm uses the visible lines, so now unrelated events can get grouped together if they share the first line of the stacktrace inside a gem (typically for me it's an HTTP client like Faraday), or even from the stdlib like Net::HTTP (e.g. on Heroku ruby is installed in the project root, under `vendor/`, see [heroku-buildpack-ruby](https://github.com/heroku/heroku-buildpack-ruby/blob/49af4ace3f7517adf0544cfd24d21759948c8e3e/lib/language_pack/ruby.rb#L181)).

### Version
* v6.0.0 and later

**Comment by kattrali** [comment]
Thanks for the detailed report, @etiennebarrie. This should be fixed in the next patch.

> It seems the grouping algorithm uses the visible lines, so now unrelated events can get grouped together, if they share the first line of the stacktrace inside a gem (typically

Which gem is it, typically?

**Comment by etiennebarrie** [comment]
Oops sorry updated the description.

**Comment by kattrali** [comment]
Thanks!
