### ISSUE TITLE
Bugsnag.log was removed in 6.0

### ISSUE THREAD

**Issue by weppos** [bugsnag/bugsnag-ruby#398]
5.5 had a `Bugsnag.log` wrapper, that was removed in 6.0 (somewhere in #320, I tried to track it but commit messages are not very self-explanatory) without any mention in the UPGRADE.

We had a middleware that used it in some cases, and after deployment it took us a while to figure out what was going on (no specific hints or crashes).

Please mention it in the upgrade page.

**Comment by Cawllec** [comment]
Hi @weppos, you're quite right, this should have been in the upgrade guide.

If you want to continue to use the logger you can access it through the `configuration` object, namely:
```
Bugsnag.configuration.info
Bugsnag.configuration.warn
Bugsnag.configuration.debug
```
I'll get the upgrade guide updated.

**Comment by kattrali** [comment]
Closed via https://github.com/bugsnag/bugsnag-ruby/pull/399
