### ISSUE TITLE
Is it possible to set repository and revision for source code tracking?

### ISSUE THREAD

**Issue by maxjacobson** [bugsnag/bugsnag-ruby#405]
👋 

### Expected behavior

I expected I would be able to do:

```ruby
Bugsnag.configure do |config|
  config.repository = "https://github.com/maxjacobson/my-great-repo"
  config.revision = "130fdf7e189a0b968fef29ad74eba55a03b0bf4f"
end
```

And then have [source code integration](https://docs.bugsnag.com/api/deploy-tracking/#source-code-integration) set up.

### Observed behavior

As far as I can tell, there's no way to include that information. Maybe it's possible by using a `before_notify_callback`...  but I didn't try that yet.

### Version

5.4.1

### Additional information

I guess this is more of a feature request or request for clarification than a bug report. Thanks in advance for your time.

**Comment by Cawllec** [comment]
Thanks for the feedback @maxjacobson,
Source code tracking isn't available through the error notifier at the moment, but is through rake/capistrano tasks in the [Bugsnag-Capistrano](https://github.com/bugsnag/bugsnag-capistrano) library.

I'll add a ticket to discuss whether we want to add this into the notifier in the future.

**Comment by maxjacobson** [comment]
@Cawllec Hey there. You know, I didn't realize this information is meant to be sent in a separate notification from a normal error notification. That makes more sense to me now. Now that I see [these docs](https://docs.bugsnag.com/api/deploy-tracking/#curl-example), I think I'm unblocked and this ought to be closed. Thanks!
