### ISSUE TITLE
Bugsnag crashes running rake task

### ISSUE THREAD

**Issue by martinstreicher** [bugsnag/bugsnag-ruby#409]
### Expected behavior
The bugsnag rake task `rake bugsnag:deploy` should tell bugsnag that new code has been pushed. See the documentation at https://docs.bugsnag.com/api/deploy-tracking/rake/

### Observed behavior
`rake` crashes with the backtrace... 

```
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'bugsnag-capistrano'.
Gem Load Error is: uninitialized constant Capistrano
Backtrace for gem load error is:
/Users/strike/.rvm/gems/ruby-2.4.1@juul/gems/bugsnag-capistrano-1.1.1/lib/bugsnag-capistrano/capistrano2.rb:32:in `<top (required)>'
/Users/strike/.rvm/gems/ruby-2.4.1@juul/gems/bugsnag-capistrano-1.1.1/lib/bugsnag-capistrano/capistrano.rb:6:in `require_relative'
/Users/strike/.rvm/gems/ruby-2.4.1@juul/gems/bugsnag-capistrano-1.1.1/lib/bugsnag-capistrano/capistrano.rb:6:in `<top (required)>'
/Users/strike/.rvm/gems/ruby-2.4.1@juul/gems/bugsnag-capistrano-1.1.1/lib/bugsnag-capistrano.rb:1:in `<top (required)>'
```

### Steps to reproduce
Follow the instructions to upgrade bugsnag 5 to 6 and follow the instructions for rake at the URL shown above. 

### Version
bugsnag 6.4.0

### Additional information
Gemfile looks like this:

```
gem 'bugsnag', '~> 6.4.0'
...

group :development do
  gem 'bugsnag-capistrano'
  gem 'capistrano'
  ...
end
```

Rakefile looks like this:

```
require File.expand_path('../config/application', __FILE__)
require 'bugsnag-capistrano/tasks'

Rails.application.load_tasks
```

bugsnag.rb looks like this:

```
Bugsnag.configure do |config|
  stages = %w(production staging)
  stages.push('development') if ENV['DEBUG_SIDEKIQ']

  config.api_key = ENV['BUGSNAG_API_KEY']
  config.ignore_classes << HTTP::ConnectionError
  config.ignore_classes << Middleware::Restart
  config.ignore_classes << Savon::SOAPFault
  config.notify_release_stages = stages
end
```

Even including capistrano does not address the issue with this line of code....

```
Bugsnag::Capistrano.load_into(Capistrano::Configuration.instance) if Capistrano::Configuration.instance
```

**Comment by Cawllec** [comment]
HI @martinstreicher, sorry for the delay, I'm looking into this now.

**Comment by martinstreicher** [comment]
I figured everyone was on holiday. Let me know if I can provide some guidance. I have not tried to reduce this to a simple test app yet.

**Comment by Cawllec** [comment]
I've had a look into this and it seems to be that rails is loading in the all the tasks even when only the rake task is required.  I've created a PR to stop loading the Capistrano tasks when Capistrano is not defined, which should fix this issue.
