### ISSUE TITLE
Sidekiq error handling is incomplete

### ISSUE THREAD

**Issue by mperham** [bugsnag/bugsnag-ruby#430]
Hi, as of Sidekiq 3.0, error handling should be done with a global error handler, not middleware:

https://github.com/mperham/sidekiq/blob/master/3.0-Upgrade.md#error-service-providers

Using your current middleware approach only catches errors in job execution.  Using a global handler catches errors **anywhere** inside Sidekiq (e.g. `on(:event)` handlers, internal exceptions, etc).

**Comment by kattrali** [comment]
Thanks, @mperham.

**Comment by Cawllec** [comment]
Hi @dja, we're expecting to have this released shortly.

**Comment by snmaynard** [comment]
This is done!
