### ISSUE TITLE
Logs don't indicate they're coming from bugsnag

### ISSUE THREAD

**Issue by swrobel** [bugsnag/bugsnag-ruby#438]
Looking at a deploy to Heroku and saw this:
`remote:        W, [2018-03-08T00:33:52.460418 #1347]  WARN -- : No valid API key has been set, notifications will not be sent`

Nothing in that message indicates it came from Bugsnag. I had to google for it which led me to this repo.

### Version
gem 6.6.4

**Comment by Cawllec** [comment]
Hi @swrobel, thanks for the feedback.  We've had some discussion over logging clarity in some of the other notifiers recently, so will be looking in to making our logs better in general.

**Comment by jfelchner** [comment]
@cawllec @kattrali that commit doesn’t fully address this issue.

**Comment by kattrali** [comment]
@jfelchner How so? Provided your log formatter does not exclude `progname`, every message from within bugsnag is marked with `[Bugsnag]`.

**Comment by jfelchner** [comment]
It solves that issue. It doesn’t solve the fact that with a properly configured initializer, spurious log messages are printed stating that the API key is invalid.

**Comment by jfelchner** [comment]
@Cawllec @kattrali what is the plan here?  This is extremely annoying.

**Comment by jfelchner** [comment]
Ok great! Can we reopen this until then?

**Comment by swrobel** [comment]
@jfelchner I'm with you here, but you're spamming my inbox when the issue I raised is actually fixed. The issue you want to track (and that I'm also tracking) is https://github.com/bugsnag/bugsnag-ruby/issues/391
