### ISSUE TITLE
Add version of bugsnag API to readme

### ISSUE THREAD

**Issue by JamesPlayer** [bugsnag/bugsnag-ruby#456]
### Expected behavior
Readme shows which version of the bugsnag API this library is using

### Observed behavior
Readme does not show which version of the bugsnag API this library is using

### Version
All

### Additional information
It would be great to know which version of the bugsnag API this library uses, as I received an email from Bugsnag warning that the default API version is changing to v2, and am not sure which version this library uses.

**Comment by kattrali** [comment]
Thanks for the report, @JamesPlayer. The email warning referred to the [Data Access API](http://bugsnagapiv2.docs.apiary.io/), which is a way to download and filter data stored on bugsnag.com. `bugsnag-ruby` (and all of our error reporting libraries use the [Error Reporting API](https://docs.bugsnag.com/api/error-reporting/) which was not affected by the deprecation of Data Access API v1.
