### ISSUE TITLE
ActionView::Template::Error grouping

### ISSUE THREAD

**Issue by unixcharles** [bugsnag/bugsnag-ruby#461]
Rails wrap view exception within `ActionView::Template::Error`.

This mess with grouping. You end up having tons of different exception grouped within  `ActionView::Template::Error`.

Would you consider adding a grouping_hash for that specific use case?

```ruby
module UngroupTemplateErrorOnBugsnag
  def bugsnag_grouping_hash
    original_exception.class.to_s
  end
end

ActiveSupport.on_load(:action_view) do
  ActionView::Template::Error.prepend(UngroupTemplateErrorOnBugsnag)
end
```

**Comment by snmaynard** [comment]
I would recommend that you email support@bugsnag.com with specific links to errors that are grouping together that shouldn't be. We can then give you some tips on how to split them or if more generally appropriate we can upstream changes to the notifier.

**Comment by Cawllec** [comment]
@unixcharles let me know when you've got in touch and I'll close this issue down.
