### ISSUE TITLE
skip_bugsnag does not work, still showing exception in Bugsnag timeline

### ISSUE THREAD

**Issue by tommybernaciak** [bugsnag/bugsnag-ruby#470]
### Description

I want to raise error but skip the bugsnag inbox.
### Issue
When I add skip_bugsnag parameter (the way ti is shown in docs) I still see this exception in bugsnag.

### Environment

Library versions:
2.8.12
production

### Example code snippet

```ruby
exception = Service.new(message, skip_bugsnag: true)
raise exception
```

**Comment by kattrali** [comment]
Thanks for the report, @tommybernaciak. Does your `Service` exception respond to `skip_bugsnag` as a method (and return a truthy value)? [Here is how it is detected within the library](https://github.com/bugsnag/bugsnag-ruby/blob/c05e4daebdd2cc4ed8fa0483c207d8c9202edfe4/lib/bugsnag.rb#L180).

**Comment by snmaynard** [comment]
Can you send support a link to an error like this or paste the link here if you prefer. There are a few possible reasons.

I would also attach a before_notify callback that looks at the raw_exceptions attribute of the report to double check that report.raw_exceptions.first.skip_bugsnag is true.

**Comment by tommybernaciak** [comment]
It is hard to verify because a callback does not work.

`undefined method 'before_notify' for Services::SomeService::Class`

`undefined method 'before_bugsnag_notify' for Services::SomeService::Class`

**Comment by snmaynard** [comment]
Take a look at the docs at https://docs.bugsnag.com/platforms/ruby/other/customizing-error-reports/#adding-callbacks and you should be able to generically add a before notify.

**Comment by tommybernaciak** [comment]
I still can't do it with code. However I changed the approach and I just ignore this error in Bugsnag Timeline. I will close this issue, but maybe it would be good to check if everything is working correctly. Thanks for help :)

**Comment by snmaynard** [comment]
Cool - we have a couple of automated tests for this https://github.com/bugsnag/bugsnag-ruby/blob/c05e4daebdd2cc4ed8fa0483c207d8c9202edfe4/spec/report_spec.rb#L1041 and https://github.com/bugsnag/bugsnag-ruby/blob/15cc05e904b8b50a7ee0b2b2722f1617ab3a76f0/features/plain_features/handled_errors.feature#L42 so it should work ok. Glad you have found a work around!
