### ISSUE TITLE
Should the API key be public?

### ISSUE THREAD

**Issue by mariogintili** [bugsnag/bugsnag-ruby#480]
### Description

The bugsnag API key for this repo is public meaning anyone can just use it and push random errors to it, if I'm not mistaken

### How to fix

Move to an env variable

[Source](https://github.com/bugsnag/bugsnag-ruby/blob/master/spec/spec_helper.rb#L53)

**Comment by fractalwrench** [comment]
Thanks for raising this @mariogintili - these are fake API keys which don't actually belong to any bugsnag project. bugsnag-ruby validates the structure of the API key which is why these placeholders are required.

**Comment by KAFILTAFISH21** [comment]
> Thanks for raising this @mariogintili - these are fake API keys which don't actually belong to any bugsnag project. bugsnag-ruby validates the structure of the API key which is why these placeholders are required.

I am able to view bugnag api key in the javascript file of a website. Is it sensitive or public ?

**Comment by hannah-smartbear** [comment]
Hi @KAFILTAFISH21 

The API key is designed as a write-only key that cannot be used for read access to any of your data. It can only be used to send data such as application error reports and sessions to BugSnag and is intended to be public on client-side platforms.

Although in theory someone could use your API key to send fake error reports to your dashboard this would be of no benefit to them and only a minor inconvenience to you.

**Comment by venkigvs2002** [comment]
is there a curl command for this

**Comment by mclack** [comment]
Hi @venkigvs2002 

Can you please elaborate on exactly what you're looking to do via cURL? You may find it useful to look at the documentation for our Data Access API, which should help you build your own cURL requests to BugSnag: https://bugsnagapiv2.docs.apiary.io/#

If you have any other questions or would like some help with making requests to BugSnag via cURL, please feel free to open a ticket with us directly by contacting support@bugsnag.com, and let us know what it is you're wanting to do.
