### ISSUE TITLE
bugsnag sourcemaps from rails

### ISSUE THREAD

**Issue by rjrobinson** [bugsnag/bugsnag-ruby#482]
### Description
We have a project that has separate bugsnag projects, and we are having an issue debugging. 

Is there a way to have the rails source map so that when a JS error fires `r is not a function` is a little easier to decipher?

### Issue
Nothing really wrong. Just trying to find if there is a defined process on this issue.

**Comment by martin308** [comment]
@rjrobinson here are our docs https://docs.bugsnag.com/platforms/browsers/js/source-maps/ for setting up JS source maps which should make your errors easier to decipher. Feel free to ping support@bugsnag.com if you have any difficulties with the setup!
