### ISSUE TITLE
LoadError: cannot load such file -- bugsnag/rake

### ISSUE THREAD

**Issue by brea9482** [bugsnag/bugsnag-ruby#484]
On newer bugsnag versions (currently running 6.8.0), we get an error when running rake tasks: `LoadError: cannot load such file -- bugsnag/rake`

Rakefile.rb looks like:

```
  require 'bugsnag/rake'
  Bugsnag.configure do |config|
    config.api_key = ENV.fetch('BUGSNAG_API_KEY')
  end

  task :run do
    raise 'testing'
  end
```

However, per the instructions here (https://docs.bugsnag.com/platforms/ruby/rake/) we need to include `require 'bugsnag/rake'`

If we remove the `/rake` such that we have `require 'bugsnag` -- the rake task runs without issue but exceptions are not percolated to bugsnag.

**Comment by Cawllec** [comment]
Hi @brea9482, the last major release, v6.0.0 actually removed the Rake integration, something we have seemingly not communicated well.  I'm updating the documentation at the moment to reflect these changes, as well as give an example of a Rake task that delivers the build notification.

In the meantime, a rake task can be built to deliver to the build API as defined [here](https://docs.bugsnag.com/api/build/).  I've also put together an example here, which will perform a build, although you may want to check the API reference to see all of the possible settings>

```
require "json"
require "net/http"
require "uri"

namespace :bugsnag do
  task :build do
    parameters = {
      "apiKey" => ENV["BUGSNAG_API_KEY"], # More API parameters can be found in the build API documentation
      "releaseStage" => ENV["BUGSNAG_RELEASE_STAGE"],
      "appVersion" => ENV["BUGSNAG_APP_VERSION"]
      "builderName" => "John Smith"
    }.reject {|k, v| v == nil}
    body = ::JSON.dump(parameters)
    Net::HTTP.post(URI("https://build.bugsnag.com/"), body, {"Content-Type" => "application/json"})
  end
end
```

**Comment by snmaynard** [comment]
@brea9482 can you instead `require 'bugsnag/integrations/rake'`? That should work in the latest version.

**Comment by brea9482** [comment]
thanks @snmaynard -- that seems to do the trick

**Comment by aandis** [comment]
> can you instead require 'bugsnag/integrations/rake'? That should work in the latest version.

fyi, the [docs](https://docs.bugsnag.com/platforms/ruby/rake/) should be updated to reflect this for rake tasks. `require 'bugsnag'` does not work.

**Comment by steve-nester-uk** [comment]
Thanks @aandis, we've amended the docs.
