### ISSUE TITLE
Mode for logging message in development?

### ISSUE THREAD

**Issue by johnmosesman** [bugsnag/bugsnag-ruby#485]
I'd like to be able to see the error message logged in development. A common use case is something like this:

```
begin
  raise "hi"
rescue StandardError => e
  Bugsnag.notify(e)
  do_something_with_the_error(e)
end
```

In production environments it works as intended: the error is sent to bugsnag and we handle the error for the user--however in development it requires more work. You have to add a pry/log of your own to see what the actual error was, and you have to track down where the error was swallowed in the first place. 

It would useful to see the exception printed in the server logs in development. Is there a way to configure this?

**Comment by Cawllec** [comment]
Hi @johnmosesman, as of yet there isn't, however it's a feature I'll raise to our products team and see what we can get done.  Thanks for bringing it up.

**Comment by snmaynard** [comment]
You can configure this by using a middleware in Bugsnag. You can define a class with a call method in it like this,

```ruby
class YourMiddlewareClass
    def call(report)
      puts report.raw_exceptions.first.inspect
      @bugsnag.call(report)
    end
end
```

and then add it to your middleware stack in your initializer `config.middleware.use(YourMiddlewareClass)`. Then every notify call will print the exception.

**Comment by snmaynard** [comment]
I'll close this issue as I think that will do what you need, feel free to reopen if I have misunderstood - thanks!
