### ISSUE TITLE
[Feature Request] Don't report POST params (or at least have the option to turn this off)

### ISSUE THREAD

**Issue by jborrey** [bugsnag/bugsnag-ruby#486]
### Description
Bugsnag, by default, should not report the params of HTTP POST requests. Basic convention is that GET params are nonsensitive (there are exceptions such as tokens in password reset links for example - this can be solved with the filter option that Bugsnag provides) and POST params are sensitive.

It is not sufficient to use the filter option to cover all possible POST params because:
  - this will be very verbose in large applications
  - the expected default is that POST params will not make there way into logging pipelines and similar systems and so a developer will probably write the code for a POST controller, without thinking about adding necessary filters to Bugsnag configuration.

Precedent for this often seen when a web framework will log a request path (with GET params) but not POST params. Rails does this for example.

Bugsnag has already made some moves in this direction such as [preventing form data from being reported](https://github.com/bugsnag/bugsnag-ruby/blob/master/CHANGELOG.md#152). This was an excellent first step, but in the age of APIs used by React/mobile apps and between microservices, I think we need to go a bit further.

This optionality is especially important with the advent of new policies like GDPR. There could be an option to turn POST param reporting on if the app developer chooses that this is okay.

**Comment by jborrey** [comment]
Looking at the way that form data is filtered (which is to add `rack.request.form_vars` to the filter list) I wonder if this change can be made by just adding `action_dispatch.request.parameters` for the Rails case?

**Comment by Cawllec** [comment]
Hi @jborrey.  Apologies for not getting to this sooner.  This seems reasonable, I'll take a look into how this can be accomplished manually for the time being, and post a response here, and recommend it to our products team.

**Comment by Cawllec** [comment]
In the mean time, you could use a callback to remove the request data from the report in the case of a POST request:

```
Bugsnag.before_notify_callbacks << proc { |report|
  if request = report.meta_data[:request]
    request[:params] = nil if request[:httpMethod] == 'POST'
  end
}
```

**Comment by jborrey** [comment]
No problem and thanks for the suggestion! I'll try it out.

**Comment by Cawllec** [comment]
Hi @jborrey, I'm closing this for now, if you have any more issues let me know.

**Comment by mtcmorris** [comment]
Hi @Cawllec - just noting that this doesn't currently work.  Is there a current method to achieve this outcome? (not log params of post requests)

**Comment by snmaynard** [comment]
This should still work - I'd recommend emailing support@bugsnag.com with a code snippet to get some help debugging.

**Comment by tomclose** [comment]
For anyone coming across this in future, `before_notify_callbacks` are [now deprecated](https://docs.bugsnag.com/platforms/ruby/rake/customizing-error-reports/#updating-events-using-callbacks), so you'll need something like:
```ruby
Bugsnag.configure do |config|
  # filter out http POST params
  filter_http_post_params = proc do |report|
    if (request = report.meta_data[:request]) && request[:httpMethod] == 'POST'
      request[:params] = '[FILTERED]'
    end
  end

  config.add_on_error(filter_http_post_params)
end
```
