### ISSUE TITLE
before_notify_callbacks not persisting in Sinatra application

### ISSUE THREAD

**Issue by brea9482** [bugsnag/bugsnag-ruby#487]
I have the below `config.ru` file. I'm trying to set the notification context to a particular string. However, when the `/` endpoint is hit, that notification context is `nil`, rather then `Campbells`. This is not the case when operating with a Rakefile so I'm trying to understand what is different about the Sinatra implementation. 

```require 'bundler/setup'
Bundler.require(:default)

$LOAD_PATH << __dir__

require 'dotenv'
Dotenv.load

require 'bugsnag'
Bugsnag.configure do |config|
  config.api_key = ENV.fetch('BUGSNAG_API_KEY')
end
Bugsnag.before_notify_callbacks << lambda { |notification|
  notification.context = 'Campbells'
}

use Bugsnag::Rack

set :raise_errors, true
set :show_exceptions, true

get '/' do
  puts Bugsnag.configuration.request_data[:before_callbacks] # nil
end

run Sinatra::Application
```

**Comment by snmaynard** [comment]
The issue is that the implementation of `Bugsnag::Rack` clears `before_notify_callbacks` so that you can do things like have a callback just for one route. We would like to support both global callbacks like you want here, as well as callbacks that just persist for the current request, but we don't have that supported right now.

What you can do to get this in the interim is add your own custom bugsnag middleware that does something like https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/middleware/callbacks.rb. If you define a class like that, you can do

```ruby
  config.middleware.use(YourMiddlewareClass)
```
Then the call method on that middleware class will be called on each notify call.

**Comment by brea9482** [comment]
Got it. Would you mind describing what the `#call(report)` method in the middleware would look like to explicitly set the context? Would it be something like:

```
    def call(report)
      report.request_data[:before_callbacks] << lambda do |notification|
        notification.context = 'Some Context'
      end

      report.request_data[:before_callbacks].each do |c|
        c.call(*[report][0...c.arity])
      end

      @bugsnag.call(report)
    end
```

**Comment by snmaynard** [comment]
Apologies I didnt reply to this sooner - but I assume you have it working now?

**Comment by brea9482** [comment]
@snmaynard no - I haven't tried it. Can you confirm if that is the right syntax? Thanks!

**Comment by snmaynard** [comment]
You can do

```ruby
    def call(report)
      report.context = 'Campbells'
      @bugsnag.call(report)
    end
```

So this is a Bugsnag middleware, so it's basically exactly what you are looking for, its a function that is called before every single notify, and not scoped to an individual request.

**Comment by brea9482** [comment]
got it - that does the trick. Thanks!

**Comment by manojmj92** [comment]
@snmaynard I have got a similar issue and I am stuck, I would appreciate your help.

I am setting a global thread variable in my `ApplicationController` around every action:

```ruby
class ApplicationController < ActionController:Base

around_action :set_global

private def set_global
 Thread.current[:global_var] = "something"
end

```

and in my initializer, I've done something like this to create a new middleware

```ruby
class Middleware
      def initialize(bugsnag)
        @bugsnag = bugsnag
      end

      def call(report)
          report.add_tab(:owner, {
            global_var: Thread.current[:global_var] 
          })
        end

        @bugsnag.call(report)
      end
 end

```

and I am using the middleware like, in initializer

```ruby
Bugsnag.configure do |config|
     config.middleware.use(MyMiddleware)
 end
```

The problem I am facing is that the middleware is always seeing ` Thread.current[:global_var]` as nil even though I am setting this value in `around_action`.

Is the order of the middlewares important here? I tried putting `MyMiddleware` to the end of the list, to the beginning of the list, in the middle - but none of them worked.

Can you please help?

**Comment by manojmj92** [comment]
@Cawllec thanks for the response! Much appreciated.

I was actually trying to integrate the https://github.com/ankane/ownership gem with bugsnag-ruby to push the owner data to bugsnag along with every report. Rollbar is already integrated with this project, so I thought Bugsnag is a rightful additon.

 This is what I have done in the ownership gem:

```ruby

module Ownership
  module Bugsnag
    class << self
      attr_reader :api_key

      def api_key=(api_key)
        @api_key = api_key
        @configure ||= configure # just once
        api_key
      end

      private

      def configure
        ::Bugsnag.configure do |config|
          config.middleware.use(Middleware)
        end
        true
      end
    end

    class Middleware
      def initialize(bugsnag)
        @bugsnag = bugsnag
      end

      def call(report)
        if (owner = Ownership.owner)
          # execution never reaches here because `owner` is nil.
          api_key = Ownership::Bugsnag.api_key
          api_key = api_key.respond_to?(:call) ? api_key.call(owner) : api_key[owner]

          report.api_key = api_key

          report.add_tab(:owner, {
            owner: owner
          })
        end

        @bugsnag.call(report)
      end
    end
  end
end
```

In a Rails initializer I have done like,

```ruby

Bugsnag.configure do |config|
  config.api_key = "key1"
end

bugsnag_keys = {}
bugsnag_keys.default = "key1"

Ownership::Bugsnag.api_key = bugsnag_keys

```
my Rails controller

```ruby

class GoalsController < ApplicationController
  owner :goals

  def index
    raise 'error'
    render json: {error: 'error'}
  end
end
```

The owner details are not being reported to bugsnag. Infact, like I have noted in the code, bugsnag middleware is seeing `Ownership.owner` as `nil`.

I have no clue why this is happening. Ownership gem actually sets the `owner` value in a controller `around_action` but Bugnsnag is not able to use it. Would you have any idea why? Anything wrong with what I am doing?

**Comment by Cawllec** [comment]
We haven't explicitly supported Ownership previously, but that shouldn't be a reason it isn't working in this case!  I can't see anything immediately wrong with what you're doing, but I'm not very familiar with how Ownership works.
I've created a ticket for this, and will take a look into why it may be happening when I can.

**Comment by manojmj92** [comment]
@Cawllec , thanks for being so proactive and helping me out! Totally appreciate it. Please do get back to me if you find anything interesting :)
