### ISSUE TITLE
Customizing error reports in a controller concern

### ISSUE THREAD

**Issue by pbougie** [bugsnag/bugsnag-ruby#490]
I'm trying to customize my error reports in a controller concern but it doesn't work and I don't understand why. This works:

```ruby
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_bugsnag_notify :add_data_to_bugsnag

  private
  def add_data_to_bugsnag(report)
    report.user = {
      id: Current.id,
      name: Current.name
    }
  end
end
```
However, this does not work:

```ruby
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Bugsnag
end

# app/controllers/concerns/bugsnag.rb
module Bugsnag
  extend ActiveSupport::Concern

  included do
    before_bugsnag_notify :add_data_to_bugsnag
  end

  private
  def add_data_to_bugsnag(report)
    report.user = {
      id: Current.id,
      name: Current.name
    }
  end
end
```
This type of refactoring works for everything else, why not Bugsnag?

**Comment by Cawllec** [comment]
Hi @pbougie, sorry this has taken so long to get to.  Are you certain that the `Bugsnag` being included in your controller is the `Bugsnag` concern, and not the `Bugsnag` module?

Through testing, this refactoring did work, but only if I explicitly required the `concern` file. Have you tried changing the name of your concern module to see if there's a difference?

**Comment by Cawllec** [comment]
For example, you could try:
```
# app/controllers/application_controller.rb
require 'concerns/bugsnag_data'
class ApplicationController < ActionController::Base
  include BugsnagData
end

# app/controllers/concerns/bugsnag_data.rb
module BugsnagData
  extend ActiveSupport::Concern

  included do
    before_bugsnag_notify :add_data_to_bugsnag
  end

  private
  def add_data_to_bugsnag(report)
    report.user = {
      id: Current.id,
      name: Current.name
    }
  end
end
```
And see if that works

**Comment by pbougie** [comment]
Renaming the module to `BugsnagData` did work. The `require` is not needed in this case. I could have sworn I renamed the module when I was trying to get this working but I can't remember now. Sorry about that and thanks for setting me straight.
