### ISSUE TITLE
Errors Reported For Local Rake Tasks

### ISSUE THREAD

**Issue by mike-stewart** [bugsnag/bugsnag-ruby#500]
### Description
I only want Bugsnag to report errors for production. It doesn't seem like there's a straightforward way to do this consistently.

Currently, bugsnag will report errors if no release_stage is set: https://github.com/bugsnag/bugsnag-ruby/blob/56f387ef36c157a2b6fbf7d9e6807d21d1e62393/lib/bugsnag/configuration.rb#L128-L132

This is a problem for rake tasks specifically. If a rake task is run without loading the environment, it will report to Bugsnag, which will use the "production" release stage by default.

The net result of this, is every time one of our developers runs a rake task locally that blows up, we get "production" error reports.

Are you open to changing the default to not report if release_stage is nil? Or is there another suggested workaround?

### Example code snippet

Rake task:
```ruby
task :test_errors_with_no_env do
  puts "Bugsnag.configuration.release_stage: #{Bugsnag.configuration.release_stage}"
  raise 'This is a test error'
end
```

Output:
```
rake test_errors_with_no_env
Bugsnag.configuration.release_stage: 
** [Bugsnag] 2018-11-27 19:16:54 -0400: Notifying https://notify.bugsnag.com of RuntimeError
rake aborted!
This is a test error
```

**Comment by t-ichii** [comment]
I have trouble by this issue too. I think solution of this issue, rake integration use environment variables  `BUGSNAG_RELEASE_STAGE`, `BUGSNAG_NOTIFY_RELEASE_STAGE`  like this([Original Source](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/integrations/rake.rb)),

```diff
   def execute_with_bugsnag(args=nil)
     Bugsnag.configuration.app_type ||= "rake"
+    Bugsnag.configuration.release_stage = ENV.fetch("BUGSNAG_RELEASE_STAGE", "production")
+    Bugsnag.configuration.notify_release_stages = [ENV.fetch("BUGSNAG_NOTIFY_RELEASE_STAGE", "production")]
     old_task = Bugsnag.configuration.request_data[:bugsnag_running_task]
     Bugsnag.configuration.set_request_data :bugsnag_running_task, self
 
     execute_without_bugsnag(args)
 
   rescue Exception => ex
     Bugsnag.notify(ex, true) do |report|
       report.severity = "error"
       report.severity_reason = {
         :type => Bugsnag::Report::UNHANDLED_EXCEPTION_MIDDLEWARE,
         :attributes => FRAMEWORK_ATTRIBUTES
       }
     end
     raise
   ensure
     Bugsnag.configuration.set_request_data :bugsnag_running_task, old_task
   end
```

**Comment by abigail-bugsnag** [comment]
Closing as this can be worked around in configuration as shown above.
