### ISSUE TITLE
Breadcrumb metadata validation fails when calling `Rails.cache.fetch`

### ISSUE THREAD

**Issue by chrisdambrosio** [bugsnag/bugsnag-ruby#539]
### Description

Bugnag generates a warning for breadcrumb metadata validation when calling `Rails.cache.fetch`:

```
Breadcrumb Read cache meta_data super_operation:Symbol has been dropped for having an invalid data type
```

### Issue

The [breadcrumb validator](https://github.com/bugsnag/bugsnag-ruby/blob/bf0383a/lib/bugsnag/breadcrumbs/validator.rb#L55-L57) checks that the metadata values are either a string, number, or boolean, but the [Rails instrumentation](https://github.com/rails/rails/blob/98a75b46468c45d4477949ed267bb8823297d815/guides/source/active_support_instrumentation.md#cache_readactive_support) for `Rails.cache.fetch` sends a symbol (`super_operation: :fetch`).

### Example Repo

https://github.com/chrisdambrosio/bugstag_testdrive

**Comment by summera** [comment]
@snmaynard any idea what the problem here might be?

**Comment by snmaynard** [comment]
So it looks like the breadcrumb code should be updated to cope with symbols. The impact will be that the operation for cache breadcrumbs is not attached to the breadcrumb and a log message is generated.

**Comment by plentz** [comment]
Seeing the same problem here. Is there an easy way to disable those log messages? Using `config.enabled_automatic_breadcrumb_types = []` just make it worse:

```
Breadcrumb Read cache meta_data super_operation:Symbol has been dropped for having an invalid data type
Automatic breadcrumb of type process ignored: Read cache
Automatic breadcrumb of type process ignored: Fetch cache hit
```

**Comment by abigail-bugsnag** [comment]
Released in https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.12.0
