### ISSUE TITLE
Allow notify_release_stages to support a regex

### ISSUE THREAD

**Issue by scalp42** [bugsnag/bugsnag-ruby#542]
### Description

We would like to be able to specify a regular expression for the stages.

Instead of:

```
stages = ['production']
1.upto(14){ |env| stages.push("dev#{env}") }
config.notify_release_stages = stages
```

We'd like to have:

```
config.notify_release_stages = ['production', 'dev*']
```

Thanks in advance for considering it.

**Comment by tomlongridge** [comment]
Thanks @scalp42 - we'll certainly add it to our list for consideration for future changes.

**Comment by tomlongridge** [comment]
After consideration we've decided to close this as we attempt to keep the notifier speed/footprint as low as possible. For users that need this, it can be achieved by performing the pattern match in `beforeNotify`.
