### ISSUE TITLE
Ignore retryable jobs from sidekiq

### ISSUE THREAD

**Issue by abhishek77in** [bugsnag/bugsnag-ruby#543]
Is it possible to not trigger notification for retryable jobs from sidekiq. The notification should only occur if job is marked as dead.

Something like - https://github.com/airbrake/airbrake/pull/831

**Comment by tobyhs** [comment]
The bugsnag gem currently doesn't have anything built-in to automatically ignore Sidekiq jobs that will be retried.

However, you can create your own middleware to use with Bugsnag to ignore errors under certain conditions. See https://github.com/bugsnag/bugsnag-ruby/issues/90#issuecomment-74778490 for an example of a middleware that prevents Bugsnag from sending errors in Sidekiq jobs where the retry count of the job is less than some threshold.

Keep in mind that if you stick with Sidekiq default settings, a job that keeps failing won't be marked dead until more than 20 day later, so waiting until a job is dead to send an error report in these cases might not be what some users desire.
