### ISSUE TITLE
Que integration can fail

### ISSUE THREAD

**Issue by mikz** [bugsnag/bugsnag-ruby#545]
### Description

Some of my jobs fail because of a statement timeout and bugsnag que integration fails to report that.

### Issue

```
Failed to notify Bugsnag of error in Que job (NoMethodError): undefined method `[]' for nil:NilClass
--
  | /opt/app-root/src/vendor/bundle/ruby/2.4.0/gems/bugsnag-6.11.1/lib/bugsnag/integrations/que.rb:7:in `block (2 levels) in <main>'
  | /opt/app-root/src/vendor/bundle/ruby/2.4.0/gems/bugsnag-6.11.1/lib/bugsnag.rb:73:in `notify'
  | /opt/app-root/src/vendor/bundle/ruby/2.4.0/gems/bugsnag-6.11.1/lib/bugsnag/integrations/que.rb:6:in `block in <main>'
  | /opt/app-root/src/vendor/bundle/ruby/2.4.0/gems/que-1.0.0.beta3/lib/que/utils/error_notification.rb:17:in `notify_error'
  | /opt/app-root/src/vendor/bundle/ruby/2.4.0/gems/que-1.0.0.beta3/lib/que/worker.rb:136:in `rescue in work_job'
  | /opt/app-root/src/vendor/bundle/ruby/2.4.0/gems/que-1.0.0.beta3/lib/que/worker.rb:90:in `work_job'
  | /opt/app-root/src/vendor/bundle/ruby/2.4.0/gems/que-1.0.0.beta3/lib/que/worker.rb:69:in `work_loop'
  | /opt/app-root/src/vendor/bundle/ruby/2.4.0/gems/que-1.0.0.beta3/lib/que/worker.rb:46:in `block in initialize'
```

### Environment

Error triggered is `PG::QueryCanceled`, which makes `Que` to pass a job `nil` to bugsnag.

**Comment by tobyhs** [comment]
Hi @mikz 

Would you mind checking if the branch at https://github.com/bugsnag/bugsnag-ruby/tree/tobyhs/check_nil_job_in_que solves your issue?

**Comment by mikz** [comment]
I'll try to reproduce it & verify the fix, but it might take a few days. Thanks!

**Comment by mikz** [comment]
@tobyhs I can't really reproduce those conditions anymore. It was under extremely high load and Que started getting database timeouts. I can't reproduce that with plain locking the table. But the change looks ok 👍

**Comment by tobyhs** [comment]
@mikz I merged a change into the `next` branch at https://github.com/bugsnag/bugsnag-ruby/pull/548. If you can't wait until the next release of bugsnag-ruby, can you use the `next` branch (at commit https://github.com/bugsnag/bugsnag-ruby/commit/90df9965cdb9fa95a45448e8464982f457a23d34 ) in your app as I'm planning on deleting the `tobyhs/check_nil_job_in_que` soon (to keep things tidy).

**Comment by mikz** [comment]
@tobyhs very thoughtful of you, fixed! Thank you.

**Comment by abigail-bugsnag** [comment]
Released in https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.12.0
