### ISSUE TITLE
Exceptions not picked up in Action Cable Channel

### ISSUE THREAD

**Issue by jeffblake** [bugsnag/bugsnag-ruby#551]
### Issue

I noticed some 500 responses in my server logs that were not being sent to Bugsnag. These originated from an Action Cable Channel action. The error was a simple `ArgumentError`: `wrong number of arguments (given 1, expected 0)`

### Environment

Bugsnag 6.11.1 (latest)
Rail 5.2.3 (latest)

Library versions:

```
  * active_record_query_trace (1.6.2)
  * autoprefixer-rails (9.6.1)
  * bugsnag (6.11.1)
  * coffee-rails (5.0.0)
  * dotenv-rails (2.7.4)
  * em-http-request (1.1.5)
  * jquery-rails (4.3.5)
  * phony_rails (0.14.13)
  * premailer-rails (1.10.2)
  * pry-rails (0.3.9)
  * rails (5.2.3)
  * rails-dom-testing (2.0.3)
  * rails-html-sanitizer (1.0.4)
  * rails-i18n (5.1.3)
  * request_store (1.4.1)
  * sass-rails (5.0.7)
  * sassc-rails (2.1.2)
  * sidekiq (5.2.7)
  * sidekiq-cron (1.1.0)
  * sidekiq-unique-jobs (6.0.13)
  * sprockets-rails (3.2.1)
  * wysiwyg-rails (2.9.0)
```

- OS / OS version:
- debug mode or production?:

Heroku, production

**Comment by mattdyoung** [comment]
This looks like it's actually an issue with the rails implementation of ActionCable, where the exceptions are suppressed and just written to the logs so there's no exception for Bugsnag to detect and report:
https://github.com/rails/rails/pull/34917

**Comment by JuanitoFatas** [comment]
Hi @mattdyoung, sorry to ask here (or it is better to get in touch with Support?) 

If an exception is raised in an `ActionCable::Channel`, do I need to explicitly report to Bugsnag? Or after rails 34917, it will automatically be picked up by Bugsnag?  I did not find [any instrumentation within the bugsnag gem](https://github.com/bugsnag/bugsnag-ruby/search?p=1&q=actioncable). Could you give me a pointer? 🙏🏼 Thanks!

**Comment by xander-jones** [comment]
Hi @JuanitoFatas 👋 . For questions and help, emailing support@bugsnag.com is the best route 👍. These errors won't be automatically captured. The PR above allows for a `rescue_from` method which you can then use to chain to a call to `Bugsnag.notify`. There's some more info in the Rails docs here on how to achieve this: https://guides.rubyonrails.org/action_cable_overview.html#server-side-components-channels-exception-handling

**Comment by mochetts** [comment]
@xander-jones why does the bugsnag docs [say that bugsnag is capturing ActionCable events](https://docs.bugsnag.com/platforms/ruby/rails/automatically-captured-data/)?

**Comment by xander-jones** [comment]
@mochetts the docs here tell us that ActionCable actions are captured as breadcrumbs, this is different to capturing errors thrown from ActionCable. Bugsnag automatically captures a breadcrumb when an ActionCable action is performed.

Breadcrumbs appear in a tab within an error event on the Bugsnag dashboard that show you what occured in the lead up to an error occuring. https://docs.bugsnag.com/platforms/ruby/rails/#logging-breadcrumbs
