### ISSUE TITLE
Prevent User IP being sent to bugsnag

### ISSUE THREAD

**Issue by fionnbharra** [bugsnag/bugsnag-ruby#553]
### Description

In my sinatra app I'm trying to prevent a user IP being sent to bugsnag. I've tried adding to the `meta_data_filters` without success:

```ruby
require 'bugsnag'

Bugsnag.configure do |config|
  config.api_key = ENV['BUGSNAG_KEY']
  config.meta_data_filters += %w[clientIp client_ip rack.request.clientIp id]
end

```
 Is it possible to filter user IP?

**Comment by mattdyoung** [comment]
Hi @fionnbharra 

Yes, it should be possible. Could you email support@bugsnag.com with details of which of your projects this relates to and a link to an error where this isn't getting filtered correctly so we can confirm which field is showing the user IP and why the callback might not be working.

Many thanks
Matt
