### ISSUE TITLE
Can not leave Breadcrumbs

### ISSUE THREAD

**Issue by dewetblomerus** [bugsnag/bugsnag-ruby#579]
### Description
I'm trying to follow this documentation to leave breadcrumbs https://docs.bugsnag.com/platforms/ruby/rails/#logging-breadcrumbs

### Issue
```
NoMethodError: undefined method `leave_breadcrumb' for Bugsnag:Module`
```

### Environment

Library versions:

```
  * bugsnag (6.0.1)
  * dotenv-rails (2.7.5)
  * pry-rails (0.3.9)
  * rails (5.2.4)
  * rails-dom-testing (2.0.3)
  * rails-html-sanitizer (1.3.0)
  * request_store (1.4.1)
  * rspec-rails (3.9.0)
  * sidekiq (6.0.3)
  * sidekiq-pro (5.0.1)
  * sprockets-rails (3.2.1)
```

- OS / OS version:
This happens on MacOS 10.15.2 and the standard `ruby:2.6.5` Docker container.
- debug mode or production?: Same on Dev and QA.

### Example code snippet

Here is a console session showing that I have Bugsnag working correctly but the error happens when I try to leave a breadcrumb:

```ruby
[15] pry(main)> Bugsnag.notify("notification")
W, [2020-01-07T15:15:25.993693 #13591]  WARN -- : Converting non-Exception to RuntimeError: "notification"
I, [2020-01-07T15:15:26.007540 #13591]  INFO -- : Notifying https://notify.bugsnag.com of RuntimeError
=> nil
[16] pry(main)> D, [2020-01-07T15:15:26.986462 #13591] DEBUG -- : Request to https://notify.bugsnag.com completed, status: 200
[16] pry(main)>
[17] pry(main)> Bugsnag.leave_breadcrumb("breadcrumb")
NoMethodError: undefined method `leave_breadcrumb' for Bugsnag:Module
```

**Comment by mattdyoung** [comment]
Hi @dewetblomerus 

You're using a very old version of bugsnag-ruby (v6.0.1). Breadcrumb support was only added in v6.11.0. We'd recommend using the latest available version v6.12.2:
https://github.com/bugsnag/bugsnag-ruby/releases

Thanks!
