### ISSUE TITLE
How to troubleshoot "ignore being signified in internal middlewares?"

### ISSUE THREAD

**Issue by swrobel** [bugsnag/bugsnag-ruby#585]
### Description
I saw an exception that generated a 500 in my logs that wasn't picked up by Bugsnag. The message is `Not notifying Stripe::CardError due to ignore being signified in internal middlewares`. This was generated in the course of a normal Rails controller action, so I don't see how middleware is involved. How do I go about figuring out why this was ignored?

### Environment

Library versions:

```
  * bugsnag (6.13.0)
  * intercom-rails (0.4.1)
  * money-rails (1.13.3)
  * premailer-rails (1.10.3)
  * que (1.0.0.beta4)
  * que-web (0.8.0 3655323)
  * rails (6.0.2.1)
  * rails-controller-testing (1.0.4)
  * rails-dom-testing (2.0.3)
  * rails-html-sanitizer (1.3.0)
  * react-rails (2.6.1)
  * request_store (1.5.0)
  * rspec-rails (4.0.0.beta4)
  * rubocop-rails (2.4.2)
  * sassc-rails (2.1.2)
  * sinatra (2.0.8.1)
  * slim-rails (3.2.0)
  * sprockets-rails (3.2.1)
```

- OS / OS version:
- debug mode or production?: production

**Comment by snmaynard** [comment]
I suspect you have an `ignore_classes` set that ignored the error. Can you confirm or paste your configuration block?

**Comment by swrobel** [comment]
Ha, so I do! Sorry about that - I guess I copied over the config from a previous project and didn't even consider that. Perhaps a more useful error message would make the cause of this more obvious, though.

**Comment by snmaynard** [comment]
Agreed!
