### ISSUE TITLE
AWS Lambda - Random OpenSSL and Timeout issue when Bugsnag.notify

### ISSUE THREAD

**Issue by wildodecisiv** [bugsnag/bugsnag-ruby#588]
### Description
I have an aws lambda function and It gets random connection issues at the time to send the notification to Bugsnag. Most of the time (60%~70%) It is not able to send the notification to Bugsnag, some times it works (30%~40%). 

### Issue

Bugsnag.notify is not sending (100%) of the times the notifications to Bugsnag, some times it sends and others it doesn't.
The error happens with or without a VPC configuration, so I think it's not an issue related to AWS VPC service.
The lambda function is able to get always data from an external api (Internet) even when Bugsnag raises connection issue.

### Environment

Library versions:
ruby: 2.5.0
aws lambda: ruby 2.5 (runtime)

```
* bugsnag (6.13.0)
```

- OS / OS version: AWS Lambda runs over Amazon Linux
- debug mode or production?:
production

### Example Repo

- [ ] Create a minimal repository that can reproduce the issue after running
  `bundle install` and `rackup` (or `rails server`, or `ruby some-script.rb`,
  etc)
- [ ] Link to it here:

### Example code snippet

```ruby
require 'bugsnag'
require 'dotenv/load'
require 'singleton'

class LoggerService
  include Singleton
  
  def initialize
   configure_bugsnag
  end

  def log(e)
   Bugsnag.notify(e)
  end

  private

  def configure_bugsnag
   Bugsnag.configure do |config|
    config.api_key = ENV['BUGSNAG_SECRET_KEY']
    config.release_stage = ENV['STAGE']
    config.notify_release_stages = %w[production test]
  end

  at_exit do
   Bugsnag.notify($ERROR_INFO) if $ERROR_INFO
  end
 end
end

# For testing purpose
error = StandardError.new('A brief description of the issue')
LoggerService.instance.log(error)
```

```
- ** [Bugsnag] 2020-03-20 18:45:40 +0000: Notification to https://notify.bugsnag.com failed, #<OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A>

- ** [Bugsnag] 2020-03-20 18:45:40 +0000: ["/var/lang/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'", "/var/lang/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'", "/var/lang/lib/ruby/2.5.0/net/http.rb:985:in `connect'", "/var/lang/lib/ruby/2.5.0/net/http.rb:920:in `do_start'", "/var/lang/lib/ruby/2.5.0/net/http.rb:909:in `start'", "/var/lang/lib/ruby/2.5.0/net/http.rb:1458:in `request'", "/var/task/vendor/bundle/ruby/2.5.0/gems/bugsnag-6.13.0/lib/bugsnag/delivery/synchronous.rb:51:in `request'", "/var/task/vendor/bundle/ruby/2.5.0/gems/bugsnag-6.13.0/lib/bugsnag/delivery/synchronous.rb:12:in `deliver'", "/var/task/vendor/bundle/ruby/2.5.0/gems/bugsnag-6.13.0/lib/bugsnag/delivery/thread_queue.rb:24:in `block in deliver'", "/var/task/vendor/bundle/ruby/2.5.0/gems/bugsnag-6.13.0/lib/bugsnag/delivery/thread_queue.rb:40:in `block (2 levels) in start_once!'"]

-  ** [Bugsnag] 2020-03-23 02:41:46 +0000: Notification to https://notify.bugsnag.com failed, #<Net::OpenTimeout: execution expired>

```

**Comment by snmaynard** [comment]
In your configuration block, you can set synchronous delivery

```ruby
Bugsnag.configure do |config|
  config.delivery_method = :synchronous
end
```

That will mean that Bugsnag will synchronously deliver the exceptions, rather than in a background thread which will guarantee delivery in your environment.

**Comment by wildodecisiv** [comment]
Thank you, It seems adding that resolved the issue. :)
