### ISSUE TITLE
config.ignore_classes should deal in strings

### ISSUE THREAD

**Issue by ngan** [bugsnag/bugsnag-ruby#589]
### Description
`config.ignore_classes` should take an array of strings instead of constants (or either?)

### Issue
As we add error classes to the `ignore_classes` we're realizing that we're inadvertently loading those classes that don't need to be loaded. It would be good if `ignore_classes` can take in an array of class names as strings since this comparison is done at the time of error anyways and the raised error can just be converted to a string for comparison.

**Comment by snmaynard** [comment]
You can include a Proc in the array, or use your own middleware/callback. See https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/middleware/ignore_error_class.rb#L15 for Proc information.

The reason we don't use strings by default is that people had typos in their ignore classes and were confused as to why they weren't being ignored.

**Comment by ngan** [comment]
> You can include a Proc in the array

Yup, this is what we plan to do.

> people had typos in their ignore classes

That's fair, I suppose. Would it be cool if the library support both constants and strings natively?

**Comment by mattdyoung** [comment]
Hi @ngan 

Thanks for the report. We're considering some improvement to the API in the future so will have a think about whether it would make sense to support this at the same time.

**Comment by ngan** [comment]
I've gotten around this with the `Proc` implementation. I'm basically copying Bugsnag's logic into my own Proc 🤷-- some I'm unblocked. If you guys haven't heard about this topic/request further, you can feel free to close this.

**Comment by xander-jones** [comment]
Hey @ngan, thanks for letting us know. We're still considering this as a change in the future, but will close out this issue for now.

**Comment by davetron5000** [comment]
I know this is closed, but a reason to support strings is to squelch this deprecation warning which is all over my development logs, based on this config:

```ruby
Bugsnag.configure do |config|
  config.api_key = ENV["BUGSNAG_API_KEY"]
  config.ignore_classes << ServiceWrappers::Intakeq::RateLimitError
end
```

```
DEPRECATION WARNING: Initialization autoloaded the constants ServiceWrappers, ApplicationService, and ServiceWrappers::Intakeq.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ServiceWrappers, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
```

I, too, will use a `Proc`, but the inability to use strings makes the feature something to avoid whenever there are app-specific exceptions.

**Comment by mattdyoung** [comment]
Hi @davetron5000 

Thanks for the info. I've re-opened this and we'll take a look at what we can do in due course.

**Comment by ngan** [comment]
Yup. We had to switch to strings because of Rails 6's deprecation message (as @davetron5000 mentions). FFIW, Sidekiq had to do a similar thing: https://github.com/mperham/sidekiq/issues/4271#issuecomment-531951294

**Comment by imjoehaines** [comment]
Strings can now be used with the [new `discard_classes` option](https://docs.bugsnag.com/platforms/ruby/other/configuration-options/#discard_classes) added in v6.14.0
