### ISSUE TITLE
Safety concern to use `thread_queue` delivery method in Resque and Sidekiq

### ISSUE THREAD

**Issue by arthurchui** [bugsnag/bugsnag-ruby#593]
We use Ruby MRI to run Resque and Sidekiq. Sometimes, our code sends reports to Bugsnag within active db transaction blocks. To avoid long transactions, we prefer to defer the API calls after committing the db transactions. 

Since v2.6 (https://github.com/bugsnag/bugsnag-ruby/issues/180), Bugsnag chose `synchronous` method for [Resque](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/integrations/resque.rb#L64) and [Sidekiq](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/integrations/sidekiq.rb#L17). https://github.com/bugsnag/bugsnag-ruby/issues/180 pointed out that Resque had an issue with ThreadQueue. 

After ~6 years, I wonder if it is safe to turn on `thread_queue` now.

**Comment by phillipsam** [comment]
Hi @arthurchui 
Unfortunately, this cannot be threaded. The reason we have chosen `synchronous` is so that the error report finishes sending before the job terminates. If this does not happen, the termination of the job interrupts the notification being sent to Bugsnag.

**Comment by arthurchui** [comment]
Hi @phillipsam . Thanks for your reply. I wonder the [`at_exit`](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/delivery/thread_queue.rb#L44) hook should send the outstanding reports to Bugsnag before the job terminates, right?

**Comment by phillipsam** [comment]
Hi @arthurchui it looks like this is something we could explore when priorities allow. Let us know if you have further comments in the meantime.

**Comment by johnkiely1** [comment]
This has now been released in [v6.17.0](https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.17.0)
