### ISSUE TITLE
how to add info to any errors which are raised by a custom Delayed Job class?

### ISSUE THREAD

**Issue by breathe** [bugsnag/bugsnag-ruby#594]
I'm using ruby `delayed_job` gem and would like to include custom application-specific information in all errors which are raised during the course of execution of a particular DelayedJob class.

I'm pretty unclear from the docs on where its safe to call

`Bugsnag.before_notify_callbacks`

Can i call this at the beginning of the `perform` method of a custom DelayedJob class in order to inject some state accessible at that time -- and expect the right thing to happen?

**Comment by phillipsam** [comment]
Hi @breathe
The callbacks are scoped to the current thread to avoid leaking request data between threads. For job queues, you need to make sure the job’s callbacks are added to `before_notify_callbacks` during job initialisation.
