### ISSUE TITLE
How to filter `unhandled` exceptions getting routed to Bugsnag?

### ISSUE THREAD

**Issue by mahendrapk** [bugsnag/bugsnag-ruby#599]
### Description
How can I stop `unhandled` exceptions getting routed to Bugsnag?

### Issue

I am a developer on a Ruby on rails multi-teanant project. Our default choice for error tracking is bugsnag. However, for data compliance reasons customers have a choice to re-route the errors to an API endpoint provided by them.

To solve this, a simple `ExceptionNotifier` interface is used throughout application code. Any piece of code, wanting to report anything, to an external system uses `ExceptionNotifier`. Finally a routing choice of customer is considered and reports get routed accordingly. **Now, this approach works well for `handled` exceptions.**

For `unhandled` exceptions, Bugsnag documentation offers below choices:
 - **auto_notify** : but it's a boolean. Setting it OFF in config will mean the whole instance won't route errors to Bugsnag. We need the granularity to consider each customers choice. Hence, I wish this could take a lambda. e.g. like `should_capture` of **Sentry**.

 - set up a lambda in `Bugsnag.before_notify_callbacks`. But in my limited experimentation, I see this is not called for `unhandled` exceptions.

 Please guide me:
 - What else can I try? I do not see any other option to limit `unhandled` exceptions.
 - Why can't auto_notify take a lambda as opposed to a TrueClass or FalseClass?

Thanks!

### Environment

Library versions:

```
  * angular-rails-templates (1.0.2)
  * angular-ui-bootstrap-rails (0.7.0.1)
  * angularjs-rails (1.2.26)
  * baby_squeel (1.3.1)
  * bugsnag (6.11.1)
  * coffee-rails (5.0.0)
  * cucumber-rails (1.4.0)
  * dotenv-rails (2.7.5)
  * factory_bot_rails (5.0.2)
  * font-awesome-rails (4.7.0.5)
  * haml-rails (2.0.1)
  * jquery-rails (4.3.5)
  * less-rails (4.0.0)
  * momentjs-rails (2.17.1)
  * rails (5.2.0)
  * rails-controller-testing (1.0.4)
  * rails-dom-testing (2.0.3)
  * rails-html-sanitizer (1.2.0)
  * rails-i18n (5.1.3)
  * request_store (1.4.1)
  * resque (1.26.0 81682d7)
  * resque-pool (0.6.0)
  * resque-scheduler (4.1.0 07d0839)
  * roadie-rails (2.1.0)
  * rspec-rails (3.7.1)
  * sass-rails (5.0.7)
  * sinatra (2.0.5)
  * sprockets-rails (3.2.1)
  * twitter-bootstrap-rails (2.2.8)
```

- OS / OS version in development: macOS 10.14.6 (18G103)
- OS / OS version in staging, production: CentOS Linux 7 (Core)

**Comment by xander-jones** [comment]
Hey @mahendrapk, the Rails callback (`before_bugsnag_notify`) will only be called (whether the error is handled, or unhandled) if it occurs within an action. You can create some custom middleware, and then add it to the Bugsnag middleware stack to configure error reports as you wish. 

In `config/initializers/bugsnag.rb`, you can add middleware for example as follows:
```
class CallbackMiddleware
  def initialize(next_callable)
    @next = next_callable
  end
  def call(report)
    report.add_tab(:diagnostics, {
      through_middleware: true
    })
    @next.call(report)
  end
end

Bugsnag.configure do |config|
  config.api_key = "YOUR_API_KEY"
  config.middleware.use(CallbackMiddleware)
end
```
