### ISSUE TITLE
Include note about tricky issue in installation docs to prevent confusion

### ISSUE THREAD

**Issue by terezka** [bugsnag/bugsnag-ruby#617]
### Description

When we were installing this gem at NoRedInk, we ran into a weird issue where handled were working fine, but unhandled exceptions didn't send. After extension debugging, we realized that it was because ruby composes gem middelwares by their order in the `Gemfile`, and the issue was that our `bugsnag` gem was listed after another gem, which also captured exceptions _but didn't reraise them_. Because of this, the exceptions never reached bugsnag. The fix was to simply move our `bugsnag` gem above the other gem in the `Gemfile`!

### Issue

This ticket is merely a suggestion to add a little note about this issue in the installation docs! It's technically none of your business, since it's just a bad interaction with another gem, but we spent almost a whole day being confused and were close to just giving up on bugsnag, so figured it might be relevant to you after all. We're of course all good now, so it's just for future users!

### Example code snippet

This produces the issue:

```
group :development do
  gem 'better_errors'
end

gem "bugsnag", "~> 6.13"
```

This fixes the issue:
```
gem "bugsnag", "~> 6.13"

group :development do
  gem 'better_errors'
end
```

---

Altogether, we really like your work- thank you!

**Comment by steve-nester-uk** [comment]
@terezka Thank you very much for the suggestion, we're going to update our docs to include a note, as you suggest.  Many thanks and glad you're enjoying using Bugsnag!
