### ISSUE TITLE
What can cause -- Not notifying SignalException due to ignore being signified in internal middlewares

### ISSUE THREAD

**Issue by breathe** [bugsnag/bugsnag-ruby#622]
### Description

Our application started outputting messages like this osmetimes --

```
Not notifying SignalException due to ignore being signified in internal middlewares
```

This is output by bugsnag here: -- https://github.com/bugsnag/bugsnag-ruby/blob/bd97e4ce8251d10d485e75c75e9d51e3e4f1b970/lib/bugsnag.rb#L90

This is a new error message for us -- and we don't understand what state could lead to this being output ...  Need help to determine whether there may be some new failure mode in our application to cause this -- or if above could be some bugsnag or bugsnag configuration issue ...

Thanks!

**Comment by snmaynard** [comment]
So we ignore `SignalException` because it is usually used by some control system to inform your server to shut down or stop processing requests or whatever. Sometimes, signals can be bad so we log this, but generally for most applications you can probably ignore this error message!

**Comment by steve-nester-uk** [comment]
Based on the answer above, assuming closed for now.  Please comment if you feel it should be reopened.
