### ISSUE TITLE
Bug with new 6.22

### ISSUE THREAD

**Issue by mjerem34** [bugsnag/bugsnag-ruby#674]
### Describe the bug
![image](https://user-images.githubusercontent.com/7813700/128884719-d594d8a9-fdf9-4b6c-8f7a-2b636b6509db.png)
LocalJumpError unexpected return

### Steps to reproduce
1. Update to 6.22

### Environment
* Bugsnag version: 6.22
* Ruby version: 2.7.2
* Bundle version: 2.1.4
* Integration framework version:
    * Que:
    * Rack
    * Rails: 6.0.2.2
    * Rake:
    * Sidekiq: 6.0.6
    * Other:

**Comment by pedrofs** [comment]
I'm facing the same issue here. Production environment went crazy after the last update.

**Comment by xander-jones** [comment]
👋. Hey, thanks for the report. We're taking a look into this now.

**Comment by imjoehaines** [comment]
Sorry for this, I've released the fix as v6.22.1
