### ISSUE TITLE
config.discard_classes not support lambda

### ISSUE THREAD

**Issue by hxx** [bugsnag/bugsnag-ruby#678]
### Description

since config.ignore_classes support lambda, but  config.discard_classes not, I need this feature to maintain the same behavior as before when config.ignore_classes deprecated

**Describe the solution you'd like**

add lambda support for config.discard_classes

**Describe alternatives you've considered**

**Additional context**

**Comment by luke-belton** [comment]
Hi @hxx 👋 

The `discard_classes` config option was introduced by #597 - it was designed to conveniently discard classes by name or regex match.

If you need to use a callback to identify particular classes for discard, you could take a look at the `add_on_error` [callback](https://docs.bugsnag.com/platforms/ruby/rails/customizing-error-reports/#discarding-events). Returning false from this callback would discard the event.
