### ISSUE TITLE
Option to disable/configure the automatic integration with ActiveJob

### ISSUE THREAD

**Issue by gustavompo** [bugsnag/bugsnag-ruby#708]
##### The problem
All errors from within ActiveJobs are being reported even when the job is being retried.

We recently realized when converting some jobs to ActiveJob that the bugsnag integration ends up reporting all errors, regardless if the job will be retried. As consequence of such approach, any network instabilities that happens during job batches ends up causing lots of noise from the existing alerts.

**Describe the solution you'd like**

It would be nice if there is an option to either:
- Configure whether the application wants to report errors being retried
- Completely disable the bugsnag `around_perform` callback  - this would allow us to setup our own error reporter

**Describe alternatives you've considered**
The approach we ended up using is to programatically traverse the `__callbacks` chain from the ActiveJob::Base on the app initialization and remove the bugsnag entry from the list.

An alternative we also considered was to have another `around_perform` callback that would intercept the error before the bugsnag's one, and only bubble it up when the job is not being retried. This though means at some sense rewrite some pieces of the ActiveJob's own retry mechanism.

**Additional context**
As it is, the reporter also completely ignores whether the error is being discarded with the `discard_on` ActiveJob option: https://edgeapi.rubyonrails.org/classes/ActiveJob/Exceptions/ClassMethods.html#method-i-discard_on

**Comment by weiyunlu** [comment]
+1, we are having the same problem, retrying a job up to 6 times would now kick off 6 bugsnags which is not an acceptable level of noise (consequent of which is our engineers on support would be pinged multiple times for the same error), so we are not upgrading to the latest version unless some kind of alternative option is introduced.

@gustavompo I believe this change came into effect on 6.22.0 so if you are able to downgrade to an earlier version you may be able to work around.

**Comment by gustavompo** [comment]
I ended up with this hacky-ish approach I'd love to get rid of when this is patched. I opted for that over downgrading to an earlier version.
This runs as one app initializer:
```
perform_callbacks = ActiveJob::Base.__callbacks[:perform]
proc_callbacks = perform_callbacks.map { |cb| [cb, cb.raw_filter.source_location.first] if cb.raw_filter.is_a?(Proc) }.compact
bugsnag_callback = proc_callbacks.find { |_cb, source| source.include?("bugsnag/") }&.first
if bugsnag_callback
   ActiveJob::Base.descendants.each do |job_class|
      job_class.__callbacks[:perform].delete(bugsnag_callback)
   end
end
```

**Comment by luke-belton** [comment]
Hi @gustavompo 👋 

Rails doesn’t provide an API that tells us if a job will be retried or discarded. For simple cases it’s possible to find this out, but both `retry_on` and `discard_on` can be given a `proc` which makes this impossible — the `proc` may have side effects so Bugsnag can’t safely call it.

Therefore Bugsnag can’t know if a job will be retried or discarded and so we report all failures. We also don’t know if a retry or discard is safe to ignore, so would likely be reporting these even if we could reliably determine that the job will be retried or discarded.

An [on error callback](https://docs.bugsnag.com/platforms/ruby/rails/customizing-error-reports/#on-error-callbacks) can be used to ignore events from a job based on the number of times it has been executed. Note this was added in Rails 5, so won’t be available if you’re running Rails 4:

```
Bugsnag.add_on_error(proc do |event|
  next unless event.metadata.key?(:active_job)

  executions = event.metadata[:active_job][:executions]

  # discard events until at least 3 executions
  # note: 'executions' counts the attempt that triggered this error, i.e. it
  #       starts at '1' and will increase each time
  if executions < 3
    false
  end
end)
```
This could then be adapted per-job, e.g. using a class method to drive the number of times a job will be attempted:
```
Bugsnag.add_on_error(proc do |event|
  next unless event.metadata.key?(:active_job)

  executions = event.metadata[:active_job][:executions]
  job_name = event.metadata[:active_job][:job_name]

  job_class = Object.const_get(job_name)

  next unless job_class.respond_to?(:retry_count)

  if executions < job_class.retry_count - 1
    false
  end
end)
```
It’s also possible to ignore all events from our built-in Active Job handler with a callback like this:
```
Bugsnag.add_on_error(proc do |event|
  if event.metadata.key?(:active_job)
    false
  end
end)
```

**Comment by weiyunlu** [comment]
^ attempted to add 

```
Bugsnag.add_on_error(proc do |event|
  if event.metadata.key?(:active_job)
    false
  end
end)
```

to our bugsnag.rb initializer, however it still seems to trigger automatically in tests, i.e.

```
 Failure/Error: expect(Bugsnag).to have_received(:notify).once
     
       (Bugsnag).notify(*(any args))
           expected: 1 time with any arguments
           received: 7 times with any arguments
```
(as a result of six retries in the test automatically notifying Bugsnag)

**Comment by johnkiely1** [comment]
We have added now the examples mentioned above to our [official documentation](https://docs.bugsnag.com/platforms/ruby/rails/customizing-error-reports/#discarding-active-job-events) around modifying/disabling the behaviour of capturing errors associated with active job events.

**Comment by aki77** [comment]
@luke-belton 

> Rails doesn’t provide an API that tells us if a job will be retried or discarded. For simple cases it’s possible to find this out, but both `retry_on` and `discard_on` can be given a `proc` which makes this impossible — the `proc` may have side effects so Bugsnag can’t safely call it.

The proc specified in retry_on or discard_on is for handling situations when a retry is abandoned or a job is discarded. Therefore, isn't it possible to make this determination without side effects?

Below is an example of using add_on_error to exclude notifications:

```ruby
config.add_on_error(proc do |event|
  next unless event.metadata.key?(:active_job)

  job_class = event.metadata[:active_job][:job_name].constantize
  handler = job_class.handler_for_rescue(event.original_error)
  handler ? false : nil
end)
```

**Comment by hannah-smartbear** [comment]
Hi @aki77,

Those procs could be pushing failed jobs to a queue, or they could be reporting them to BugSnag as handled errors, or something else completely. We can’t call them ourselves without side effects because Rails will also call them, and then the failed job would be added to the queue twice, reported to BugSnag twice, etc.

**Comment by aki77** [comment]
@hannah-smartbear 

The `handler_for_rescue` method should be able to determine whether the error is specified by either `discard_on` or `retry_on`.
In fact, as shown in the sample code, simply calling `handler_for_rescue` for this check should not trigger any procedure execution. 
Are you suggesting that merely using `handler_for_rescue` for this check is insufficient?

https://github.com/rails/rails/blob/888d28460f5bd1444eeb171cb827cd91739c3759/activesupport/lib/active_support/rescuable.rb#L90C11-L121

**Comment by hannah-smartbear** [comment]
Hi @aki77, 

Thanks for pointing this out. 

Unfortunately it wouldn’t be something that we would consider adding even if that method is a sufficient check, as we don’t want to ignore events from job failures that would be retried because we can’t know if the error is safe to ignore. For example this could completely hide bugs if the retries succeed. 

We would recommend using [my colleague Luke’s code snippets](https://github.com/bugsnag/bugsnag-ruby/issues/708#issuecomment-972790862) if you would like to ignore events.
