### ISSUE TITLE
Does there exists an offline bugsnag-server, perhaps a sister project?

### ISSUE THREAD

**Issue by andxyz** [bugsnag/bugsnag-ruby#724]
# Description

I like to work offline, on my local machine typically on a rails or ruby project.

I am looking for perhaps a "sister project" to have an "offline" bugsnag-server.
I often run code for my "app" locally, and I set some configs for:

```ruby
config.set_endpoints(
  "http://127.0.0.0:9090/bugsnag/events",
  "http://127.0.0.0:9090/bugsnag/sessions"
)
```

And then I run a local http server that spits out the json that is sent to `127.0.0.0:9090`

## Describe the solution you'd like

I was hoping there was an official solution, my solution is rather janky and my "web-ui" is raw pretty printed json that is spit out to stdout. 

mine looks like this:

![andxyz-2022-06-07-10-28-03](https://user-images.githubusercontent.com/225196/172405812-bb954492-e838-46bb-9d47-6e256a15fa2a.png)

I am looking for:
- An official Bugsnag solution
- a Server with a better ui and perhaps some poormans searching or sorting.
- Mostly I would truly appreciate a nicer view of the stacktrace, locally

## Describe alternatives you've considered

Writing my own, making it a tab better than my current lazy solution, of a local offiline bugsnag-server.

## Additional context

Here is a link to my poormans server https://github.com/andxyz/debug-json-app

I run it with:

```shell
~/code/debug-json-app (master)
$ RACK_ENV=development bundle exec unicorn --config-file unicorn_conf.rb config.ru
```

**Comment by luke-belton** [comment]
Hi @andxyz - thanks for raising this. Unfortunately this isn't something that we'd be able to work on so I'm going to close this issue for now.

I can see why you find this useful during your offline local development, so feel free to maintain your own solution and you could see whether there's any interest from the community to help you out with your efforts!
