### ISSUE TITLE
`add_on_error` doesn't get called back for handled errors

### ISSUE THREAD

**Issue by alexibz** [bugsnag/bugsnag-ruby#729]
### Describe the bug
I added the `add_on_error` callback in `config/initializers/bugsnag.rb`:
```ruby
  config.add_on_error(proc do |event|
    metadata = event.meta_data.dig(:sidekiq, :msg, "args", 0, "arguments", 0, "metadata")
    event.add_metadata(:params, { metadata: metadata }) if metadata
  end)
```
It works well for unhandled exception, but handled exceptions, triggered through `Bugsnag.notify` aren't going through this callback.

### Environment
* Bugsnag version: 6.24.2
* Ruby version: ruby 3.1.2p20
* Bundle version: 2.2.33
* Integration framework version:
    * Rails: 7.0.4
    * Sidekiq: 6.5.7

**Comment by luke-belton** [comment]
Hi @alexibz - I'm not sure if it's just a typo above, but you should be accessing the event's metadata via `event.metadata` (rather than `event.meta_data` as per your code snippet). Additionally are you sure the sidekiq path in your hash resolves to something non-`nil` for your `Bugsnag.notify` calls? Any serialized metadata keys with `null` values won't be displayed in the Bugsnag dashboard once the event has been received.

**Comment by alexibz** [comment]
Hi @luke-belton, thank you for the response - my issue was that one of the keys was `null`, but with a caveat. In the code I sometimes directly call `Bugnsag.notify` and directly add metadata:
```ruby
      Bugsnag.notify(e) do |event|
        params = {id: @id}
        params[:code] = defined?(e.class.code) ? e.class.code : :exception
        event.add_metadata(:params, params)
      end
```
That code was being called in a class method, so `@id` didn't exist. I also have a `add_on_error` callback that adds the relevant information:
```
  config.add_on_error(proc do |event|
    id = event.meta_data.dig("id")
    event.add_metadata(:params, { shop_id: shop_id }) if shop_id
end
```
What I observed is that if an entry is set to `null`, like `id` in the class method, it won't be overwritten by the callback.

As for the `meta_data` I believe this was an old syntax.

**Comment by luke-belton** [comment]
Hi @alexibz - the behaviour you have observed with `nil` values not being overwritten has changed in more recent versions of `bugsnag-ruby`, see  https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/utility/metadata_delegate.rb#L17-L35. I'd recommend upgrading to the latest version, https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.25.0.

If this doesn't resolve this problem let us know and we can investigate this further 👍
