### ISSUE TITLE
skip_bugsnag is not functioning

### ISSUE THREAD

**Issue by jibiking** [bugsnag/bugsnag-ruby#791]
### Describe the bug
The description in the official documentation states that even when using the "skip_bugsnag" configuration, notifications to Bugsnag are not stopping.
Has the bug in this issue not been resolved?
https://github.com/bugsnag/bugsnag-ruby/issues/470

### Steps to reproduce

sample code↓
```
    begin
      raise StandardError
    rescue StandardError => exception

      Bugsnag.notify(exception)
      exception.instance_eval { def skip_bugsnag; true; end }

      raise ActionController::RoutingError, 'not_found'
    end
```

### Environment
- ruby3.1.4
- raills6.1
- gem bugsnag6.26.0

**Comment by imjoehaines** [comment]
Hey, @jibiking

`skip_bugsnag` works on the specific instance of the exception you apply it to. In your example you're applying it to `exception` but raising a `RoutingError` afterwards. That means that the `RoutingError` doesn't have `skip_bugsnag` applied to it, which results in it being reported to Bugsnag

To make it work you'd need to apply `skip_bugsnag` to the `RoutingError` before raising it, like this:

```ruby
begin
  raise StandardError
rescue StandardError => exception
  Bugsnag.notify(exception)

  routing_error = ActionController::RoutingError.new('not_found')
  routing_error.instance_eval { def skip_bugsnag; true; end }

  raise routing_error
end
```

If you want to ignore _all_ `RoutingError` exceptions, take a look at the [`discard_classes` configuration option](https://docs.bugsnag.com/platforms/ruby/rails/configuration-options/#discard_classes)

Hope that helps!
