### ISSUE TITLE
Breadcrumb meta_data validation fails while using ActionMailer

### ISSUE THREAD

**Issue by Studenich** [bugsnag/bugsnag-ruby#802]
### Describe the bug
Breadcrumb meta_data validation fails while using ActionMailer:
`Breadcrumb ActionMail delivered meta_data date:DateTime has been dropped for having an invalid data type`

The email is delivered successfully btw if I catch this exception like this:
```
begin
  CompanyInvoiceMailer.report(email, report).deliver_now
rescue => exception
  exception.message
end
```

### Environment
* Bugsnag version: 6.13.0
* Ruby version: 2.7.4
* Bundle version: 2.1.4
* Integration framework version:
    * Rails: 6.0.2.2
    
 Is this something similar with this issue? https://github.com/bugsnag/bugsnag-ruby/issues/539

**Comment by imjoehaines** [comment]
Hi @Studenich, the validation on breadcrumb metadata types was removed in [v6.19.0](https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.19.0) so updating your bugsnag version should allow you to attach `DateTime` values to your breadcrumbs

The latest release is [v6.26.0](https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.26.0)

**Comment by Studenich** [comment]
@imjoehaines Thanks a lot, it definately has helped me!
