### ISSUE TITLE
Allow to notify about sidekiq error only after several insuccessful retries

### ISSUE THREAD

**Issue by bogdan** [bugsnag/bugsnag-ruby#90]
We are sending emails with sidekiq workers that are monitored for exceptions by bugsnag.

There are a lot of one time exceptions like `IO::EAGAINWaitReadable`.
The 5 seconds downtime of the mail  server (e.g it is redeployed) results in hundreds of such errors.

Can we setup bugsnag-sidekiq to notify about exceptions only after several unsuccessful retries?

**Comment by mihar** [comment]
Any updates on this? We're trying to solve the exact same problem.

**Comment by mihar** [comment]
I've found the culprit.

If you look at [sidekiq.rb](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/sidekiq.rb#L24-L36) you can see two different approaches being taken whether your Sidekiq is older than version 3 or newer.

If Sidekiq is older then version 3, this works correctly, as the method [`Notification#add_tab`](https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/notification.rb#L110-L120) adds the tab data to the `@meta_data` variable as well.

If Sidekiq if version 3 or newer, it uses the new `config.error_handlers` callback mechanism to call `Notification.auto_notify` straight away.

The difference with the latter approach is, that it sets the Sidekiq data into the `overrides` parameter and that gets set to the `@overrides` instance variable inside the `Notification` object. 

In that case, it never gets to setting the `@meta_data` variable, as it just formats it straight into (`payload_event[:metaData]`)[https://github.com/bugsnag/bugsnag-ruby/blob/master/lib/bugsnag/notification.rb#L230].

So the solution would be to always set the `@meta_data` variable from the `@overrides` in `Notification#deliver` before the middleware/callbacks.

**Comment by snmaynard** [comment]
I will try and get around to doing a fix for this this week. Its very much related to #192 and #193 and probably requires a slight architectural change to get the order of all the various callbacks and hooks to be intuitive and correct (hence the slight delay).

Well spotted about the version 3 issue with Sidekiq @mihar!

**Comment by bogdan** [comment]
Patiently waiting for a moment when my inbox not gonna look like that: ![img](http://take.ms/XlxKi)

**Comment by jfelchner** [comment]
@bogdan you're a much more patient person than me. :) We had two issues with BugSnag that, after months of not being fixed, we switched to Honeybadger.

**Comment by bogdan** [comment]
@jfelchner I'll take a look at honeybadger, thanks

**Comment by ConradIrwin** [comment]
This is fixed in `v2.8.0`. The necessary configuration is as follows:

```ruby
class SidekiqMiddleware
  def initialize(bugsnag)
    @bugsnag = bugsnag
  end

  def call(notification)
    if notification.meta_data[:sidekiq] && notification.meta_data[:sidekiq]["retry_count"] < 3
      notification.ignore!
      return
    end

    @bugsnag.call(notification)
  end
end

Bugsnag.configure do |config|
   ...
   config.middleware.use SidekiqMiddleware
end
```


Thanks for your patience!

**Comment by mihar** [comment]
@ConradIrwin any ideas, why Bugsnag with the middleware would start grouping errors on the `@bugsnag.call` line?

**Comment by ConradIrwin** [comment]
Not immediately, but I can think of a few edge-cases that might be problematic. Can you send me a link to an error on your dashboard with this problem (either here, or conrad.irwin@bugsnag.com)

**Comment by sahin** [comment]
@ConradIrwin hi, we have many different retry counts

how about 

````
    if notification.meta_data[:sidekiq] && notification.meta_data[:sidekiq]["retry_count"] < notification.meta_data[:sidekiq]["retry"]
````

**Comment by ConradIrwin** [comment]
@sahin If that works for you, go for it. For us, we notify bugsnag on the first occurrence of an error so that we can debug it before sidekiq has lost track of the job.

**Comment by sahin** [comment]
As you might now,  in sidekiq after the retires it is going to dead queue.

Is it code for sidekiq < 3

On Wednesday, March 18, 2015, Conrad Irwin <notifications@github.com> wrote:

> @sahin <https://github.com/sahin> If that works for you, go for it. For
> us, we notify bugsnag on the first occurrence of an error so that we can
> debug it before sidekiq has lost track of the job.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bugsnag/bugsnag-ruby/issues/90#issuecomment-83076878>.
>


-- 

Best,
Sahin


-- 
Sahin Boydas
Founder/CTO



Download MovieLaLa: https://itunes.apple.com/app/id869901634

w: MovieLaLa.com
v:  MovieLaLa.com/angel
f:  facebook.com/movielala
t:  movielala.tumblr.com
a: downtown Palo Alto, CA

**Comment by sandstrom** [comment]
Does anyone know the canonical way of ignoring exceptions where `retry_count` is lower than Y?

I've tried [everything from the docs](https://docs.bugsnag.com/platforms/ruby/sidekiq/reporting-handled-errors/) as well as the things outlined here.

Sidekiq ~3.2
Bugsnag ~5.0

**Comment by sandstrom** [comment]
It would be great if the Bugsnag documentation could provide clear, simple information on how its Sidekiq-integration works.

I finally got it working with something like this (hopefully it can help someone else):

```ruby
# config/initializers/bugsnag.rb

class SidekiqBugsnagMiddleware

  # With Bugsnag callbacks are treated as request state and are registered on the current job only.
  # Because of this we cannot use the regular `Bugsnag.configure` block below. Instead we use a
  # Sidekiq middleware (which run before each job) and setup the callback before each job runs.

  BUGSNAG_CALLBACK = lambda do |bug_report|
    if sidekiq_data = bug_report.meta_data[:sidekiq]

      # this value is nil for the first job attempt
      retry_count = sidekiq_data[:msg]['retry_count']

      if !retry_count || retry_count && retry_count < 5
        bug_report.ignore!
      end
    end
  end

  def initialize(options = nil)
  end

  def call(worker, msg, queue)
    # Guard against changes in the behaviour described above. Otherwise we'd risk adding to
    # the notify callback queue for every job invocation, and that would quickly spiral out of control.
    unless Bugsnag.before_notify_callbacks.include?(BUGSNAG_CALLBACK)
      Bugsnag.before_notify_callbacks << BUGSNAG_CALLBACK
    end

    yield
  end
end

Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    chain.add SidekiqBugsnagMiddleware
  end
end

```

**Comment by bogdan** [comment]
Newer approach from documentation:

https://docs.bugsnag.com/platforms/ruby/rails/customizing-error-reports/#discarding-events
